### ISSUE TITLE
Test_org_eclipse_swt_printing_Printer#test_getPrinterList fails on windows-2022

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.swt#104]
I have enabled os specific tests now, unfortunately the Printer test fails on windows-2022:

https://github.com/eclipse-platform/eclipse.platform.swt/runs/6346732956

> java.lang.AssertionError: printer list contains items even though there are no printers expected:<0> but was:<2>
> 	at org.junit.Assert.fail(Assert.java:89)
> 	at org.junit.Assert.failNotEquals(Assert.java:835)
> 	at org.junit.Assert.assertEquals(Assert.java:647)
> 	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_printing_Printer.test_getPrinterList(Test_org_eclipse_swt_printing_Printer.java:170)

**Comment by akurtakov** [comment]
Test case has special handling for Linux to expect "1" aka "file print backend" as it's always there on Linux. Is Windows-2022 version 11? Maybe it added some default backends by default and there needs to be some adjustment to expectations based on Windows 11? Worst case would be if this VM is not "pristine" Windows 11 and has these "printers" due to software extra installed as in that case we can't do much as the goal is to test SWT on as pristine as possible OS so we can set expectations.

**Comment by laeubi** [comment]
I have now windows-2022 at hand, maybe a first enhancement would be to include the printers found in the error output, I'll try this right now.

Beside that, the test seems really strange to assume there is a certain number of printers, how does this improve the coverage of errors? I assume most users have different printer settings so this test won't work most of the time on a developers machine.

**Comment by akurtakov** [comment]
I guess the question here is more about @niraj-modi as windows is not my thing.

**Comment by laeubi** [comment]
The more useful message now is:

> printer list contains items even though there are no printers, printers from list are: PrinterData {driver = winspool, name = Microsoft XPS Document Writer}, PrinterData {driver = winspool, name = Microsoft Print to PDF} expected:<0> but was:<2>

So I think this could be adjusted as it is with GTK ...

**Comment by niraj-modi** [comment]
At-least on Windows printers can be classified in 2 types:
1. The real physical printer.
2. There are some non-hardware printers which are per-configured by default, say on Win10 I see below list:
- Fax
- OneNote (Desktop)
- Microsoft Print to PDF
- OneNote for Windows 10
- Microsoft XPS Document Writer

![image](https://user-images.githubusercontent.com/92304759/167355526-4363c56a-a07a-4c1b-a359-219de8e1cbbd.png)

Looks like Windows-2022 has some new default configuration, for which this test case needs to adjusted.

**Comment by laeubi** [comment]
I have now enhanced the test case to check for this default printers on windows.
