### ISSUE TITLE
macosx.aarch64 jnilib files in git repo corrupt?

### ISSUE THREAD

**Issue by tobiasmelcher** [eclipse-platform/eclipse.platform.swt#1077]
**Describe the bug**
When I import project eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64 from the github repository on commit 50d7ef7233792599d6331b19f0d040a0d36539df, I am getting following exception when running a simple sample SWT application with the imported SWT project.

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library.
 Reasons: 
	/Users/.../git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4964r8.jnilib: dlopen(/Users/.../git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4964r8.jnilib, 0x0001): tried: '/Users/.../git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4964r8.jnilib' (not a mach-o file), '/System/Volumes/Preboot/Cryptexes/OS/Users/.../git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4964r8.jnilib' (no such file), '/Users/.../git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/libswt-cocoa-4964r8.jnilib' (not a mach-o file)
	no swt-cocoa in java.library.path: /Users/.../git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64
	no swt in java.library.path: /Users/.../git/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64
	Can't load library: /Users/.../.swt/lib/macosx/aarch64/libswt-cocoa-4964r8.jnilib
	Can't load library: /Users/.../.swt/lib/macosx/aarch64/libswt-cocoa.jnilib
	Can't load library: /Users/.../.swt/lib/macosx/aarch64/libswt.jnilib

	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:340)
	at org.eclipse.swt.internal.Library.loadLibrary(Library.java:249)
	at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	at org.eclipse.swt.widgets.Display.<clinit>(Display.java:110)
	at Snippet1.main(Snippet1.java:48)
```

If I change the constants MAJOR_VERSION, MINOR_VERSION, REVISION in class Library to a version number which exists in my /Users/.../.swt/lib/macosx/aarch64 folder, then everything works fine. 

It looks like that the binaries stored in the git repo are not valid for macosx.aarch64. 
Could you please check?

Thanks a lot,
Tobias

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS

**Comment by tobiasmelcher** [comment]
I will close the issue.
It is an LFS issue. 

The content of the jnilib files looks like this:
```
version https://git-lfs.github.com/spec/v1
oid sha256:ab3722b8f80192fa503111f18f4825e1885ed4afecee655fd28868a5d02cacf9
size 51952
```
