### ISSUE TITLE
Test_org_eclipse_swt_widgets_DateTime fails on mac

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.swt#1097]
since two I-Builds the tests fail - for example

```
java.lang.AssertionError: expected:<2> but was:<1>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_widgets_DateTime.test_setTimeIII(Test_org_eclipse_swt_widgets_DateTime.java:605)
```

see https://ci.eclipse.org/releng/job/AutomatedTests/job/ep432I-unit-macM1-java17/14/testReport/
https://download.eclipse.org/eclipse/downloads/drops4/I20240310-0340/testresults/html/org.eclipse.swt.tests_ep432I-unit-macM1-java17_macosx.cocoa.aarch64_17.html

**Comment by iloveeclipse** [comment]
Seem to work in https://download.eclipse.org/eclipse/downloads/drops4/I20240313-1800/testResults.php
