### ISSUE TITLE
Test_org_eclipse_swt_custom_CCombo.test_paste fails on win on I-Builds

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.swt#1098]
```
org.junit.ComparisonFailure: :a: expected:<1[23]456> but was:<1[]456>
	at org.junit.Assert.assertEquals(Assert.java:117)
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_custom_CCombo.test_paste(Test_org_eclipse_swt_custom_CCombo.java:149)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

https://ci.eclipse.org/releng/job/AutomatedTests/job/ep432I-unit-win32-java17/13/testReport/
https://download.eclipse.org/eclipse/downloads/drops4/I20240310-0340/testresults/html/org.eclipse.swt.tests_ep432I-unit-win32-java17_win32.win32.x86_64_17.html

**Comment by fedejeanne** [comment]
Since this doesn't fail in all I-Build, this issue might be a duplicate of #106 (see https://github.com/eclipse-platform/eclipse.platform.swt/issues/106#issuecomment-1620774289)
