### ISSUE TITLE
I20240312-1800 failed many junit related to "width"

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.swt#1105]
https://download.eclipse.org/eclipse/downloads/drops4/I20240312-1800/testResults.php

for example  IOConsoleFixedWidthTests or
```
java.lang.NullPointerException: Cannot load from int array because "this.fIndentation" is null
at org.eclipse.jface.text.source.LineNumberRulerColumn.getWidth(LineNumberRulerColumn.java:477)
at org.eclipse.jface.text.source.LineNumberChangeRulerColumn.getWidth(LineNumberChangeRulerColumn.java:262)
at org.eclipse.ui.internal.texteditor.LineNumberColumn.getWidth(LineNumberColumn.java:136)
at org.eclipse.jface.text.source.CompositeRuler.getWidth(CompositeRuler.java:673)
...
at org.eclipse.ant.tests.ui.editor.AntEditorTests.testAugmentMissingId(AntEditorTests.java:304)
```

There where  4 changes to "width" yesterday. (for example https://github.com/eclipse-platform/eclipse.platform.ui/pull/1716) But i could not reproduce the fails locally.

@shubhamWaghmare-sap @BeckerWdf can you investigate?

**Comment by iloveeclipse** [comment]
Jörg, the nightly build is broken due incompatible SWT change, that will be reverted. Don't need to create bugs based on this build results.
https://github.com/eclipse-platform/eclipse.platform.swt/pull/1101

**Comment by BeckerWdf** [comment]
They change in #1716 is in CTabRendering I don't see how this is related to LineNumberRulerColumn

**Comment by iloveeclipse** [comment]
I've triggered new SDK build with reverted https://github.com/eclipse-platform/eclipse.platform.swt/pull/1101 to get clean test results for latest changes, see https://ci.eclipse.org/releng/job/Builds/job/I-build-4.32/19/

Closing this one.
