### ISSUE TITLE
StyledText IME (Japanese) error 

### ISSUE THREAD

**Issue by tueterich** [eclipse-platform/eclipse.platform.swt#1162]
IllegalArgumentException at org.eclipse.swt.custom.DefaultContent.getLineAtOffset(575). 
[ime_exception.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/14865622/ime_exception.txt)

This happens when you press CTRL+BACKSPACE when the IME Popup is open and some text is already present in a StyledText Control.

![screenshot_ime](https://github.com/eclipse-platform/eclipse.platform.swt/assets/15818853/b7891a7e-0749-4955-8b3e-bd05461c3aac)

Steps to reproduce:
- Launch the attached Snippet and focus the StyledText Control
- Switch Keyboard Settings to Japanese (Microsoft-IME)
- Activate Hiragana or any other Option from the IME Menu
- Type something and choose a suggestion from the IME Popup
- Type something else so the IME Popup opens again
- Press CTRL+BACKSPACE while the Popup is open

There are some other cases where the exception is thrown when using the IME but I don't know how to reproduce them:
[ime_exception_2.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/14872705/ime_exception_2.txt)

OS: Win 11

Tested with:
Oracle JDK 8 / SWT 4.919 
and 
Corretto JDK 21 and SWT 4.963

Snippet:
[StyledTextIMEErrorSnippet.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/14872723/StyledTextIMEErrorSnippet.txt)

**Comment by SyntevoAlex** [comment]
Full exception text from attached file:
```
Exception in thread "main" java.lang.IllegalArgumentException: Argument not valid
	at org.eclipse.swt.SWT.error(SWT.java:4576)
	at org.eclipse.swt.SWT.error(SWT.java:4510)
	at org.eclipse.swt.SWT.error(SWT.java:4481)
	at org.eclipse.swt.custom.DefaultContent.error(DefaultContent.java:682)
	at org.eclipse.swt.custom.DefaultContent.getLineAtOffset(DefaultContent.java:575)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:1141)
	at org.eclipse.swt.custom.StyledTextRenderer.getTextLayout(StyledTextRenderer.java:871)
	at org.eclipse.swt.custom.StyledTextRenderer.calculate(StyledTextRenderer.java:292)
	at org.eclipse.swt.custom.StyledTextRenderer.calculateClientArea(StyledTextRenderer.java:321)
	at org.eclipse.swt.custom.StyledText.resetCache(StyledText.java:8029)
	at org.eclipse.swt.custom.StyledText.handleTextChanged(StyledText.java:6287)
	at org.eclipse.swt.custom.StyledText$5.textChanged(StyledText.java:5723)
	at org.eclipse.swt.custom.StyledTextListener.handleEvent(StyledTextListener.java:74)
	at org.eclipse.swt.custom.DefaultContent.sendTextEvent(DefaultContent.java:810)
	at org.eclipse.swt.custom.DefaultContent.replaceTextRange(DefaultContent.java:803)
	at org.eclipse.swt.custom.StyledText.modifyContent(StyledText.java:7366)
	at org.eclipse.swt.custom.StyledText.sendKeyEvent(StyledText.java:8230)
	at org.eclipse.swt.custom.StyledText.doDeleteWordPrevious(StyledText.java:2609)
	at org.eclipse.swt.custom.StyledText.invokeAction(StyledText.java:7161)
	at org.eclipse.swt.custom.StyledText.handleKey(StyledText.java:6018)
	at org.eclipse.swt.custom.StyledText.handleKeyDown(StyledText.java:6045)
	at org.eclipse.swt.custom.StyledText.lambda$installListeners$1(StyledText.java:5743)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4145)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1055)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1079)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1064)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1106)
	at org.eclipse.swt.widgets.Widget.sendKeyEvent(Widget.java:1102)
	at org.eclipse.swt.widgets.Widget.wmChar(Widget.java:1489)
	at org.eclipse.swt.widgets.Control.WM_CHAR(Control.java:4888)
	at org.eclipse.swt.widgets.Canvas.WM_CHAR(Canvas.java:353)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4768)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:348)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:4784)
	at org.eclipse.swt.internal.win32.OS.DispatchMessageW(Native Method)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(OS.java:2309)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3559)
	at StyledTextIMEErrorSnippet.main(StyledTextIMEErrorSnippet.java:32)
```

**Comment by jukzi** [comment]
@tueterich please try with https://github.com/eclipse-platform/eclipse.platform.swt/pull/1176

**Comment by tueterich** [comment]
> @tueterich please try with #1176

I would love to test this fix but I have some troubles using the SWT Sources instead of a compiled swt.jar. 
I'm currently trying to figure out why I can't run any snippets when using your (or even the swt-master) branch.

**Comment by jukzi** [comment]
@tueterich there is a description to set up a working Workspace including SWT sources at
https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

**Comment by tueterich** [comment]
> @tueterich there is a description to set up a working Workspace including SWT sources at https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

Tried that and followed the instructions, but it results in the same error message. 

`Exception in thread "main" java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons: 
C:\Users\*user_id*\platform-master\git\eclipse.platform.swt\binaries\org.eclipse.swt.win32.win32.x86_64\swt-win32-4965r6.dll: %1 ist keine zulässige Win32-Anwendung
no swt-win32 in java.library.path: C:\Users\*user_id*\platform-master\git\eclipse.platform.swt\binaries\org.eclipse.swt.win32.win32.x86_64
no swt in java.library.path: C:\Users\*user_id*\platform-master\git\eclipse.platform.swt\binaries\org.eclipse.swt.win32.win32.x86_64
Can't load library: C:\Users\*user_id*\.swt\lib\win32\x86_64\swt-win32-4965r6.dll
Can't load library: C:\Users\*user_id*\.swt\lib\win32\x86_64\swt-win32.dll
Can't load library: C:\Users\*user_id*\.swt\lib\win32\x86_64\swt.dll`

**Comment by jukzi** [comment]
> , but it results in the same error message.

Sometimes i get such message too. then i just rename the .dll(s) to the version filename that is expected
for example
binaries\org.eclipse.swt.win32.win32.x86_64\swt-win32-4965r5.dll
->
binaries\org.eclipse.swt.win32.win32.x86_64\swt-win32-4965r6.dll
.
With an OOmphed workspace you can also try Help/2Perform Setup Tasks".
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/51790620/37bc967f-8c91-48b3-92aa-cb8ec43e1b43)
which should update to the current build.

**Comment by tueterich** [comment]
> > , but it results in the same error message.
> 
> Sometimes i get such message too. then i just rename the .dll(s) to the version filename that is expected for example binaries\org.eclipse.swt.win32.win32.x86_64\swt-win32-4965r5.dll -> binaries\org.eclipse.swt.win32.win32.x86_64\swt-win32-4965r6.dll . With an OOmphed workspace you can also try Help/2Perform Setup Tasks". ![image](https://private-user-images.githubusercontent.com/51790620/323546007-37bc967f-8c91-48b3-92aa-cb8ec43e1b43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzQwOTcsIm5iZiI6MTcxMzQzMzc5NywicGF0aCI6Ii81MTc5MDYyMC8zMjM1NDYwMDctMzdiYzk2N2YtOGM5MS00OGIzLTkyYWEtY2I4ZWM0M2UxYjQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDA5NDk1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ1ZWQ1MjY4MDFiYTgzOTQ4NWUyZjc0M2VjMzVjMDYxNTIwM2JiNzkwZWUxNTZmYTk0M2YyNTZjNzAwMjM3ZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-3gz9gD-7h4PWUQp6kJ22_Ql4PYSLNwbqVhLOgEcEQI) which should update to the current build.



Thanks! There was a .dll file but it was only 1KB in size. Renaming the other .dll worked.

I am no longer able to reproduce this bug. Seems fine. Ty!
