### ISSUE TITLE
ubuntu 22.04 Test_org_eclipse_swt_custom_StyledText fails

### ISSUE THREAD

**Issue by laeubi** [eclipse-platform/eclipse.platform.swt#118]
See this check: https://github.com/eclipse-platform/eclipse.platform.swt/runs/6383167193

```
java.lang.AssertionError: expected:<87> but was:<174>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:647)
	at org.junit.Assert.assertEquals(Assert.java:633)
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_custom_StyledText.test_caretSizeAndPositionVariableGlyphMetrics(Test_org_eclipse_swt_custom_StyledText.java:5109)
```

**Comment by akurtakov** [comment]
I haven't seen the failure in long time plus ubuntu 22.04 is no longer of interest.
