### ISSUE TITLE
Exception when creating GC from Image inside a thread on Windows

### ISSUE THREAD

**Issue by ddscharfe** [eclipse-platform/eclipse.platform.swt#1288]
**Describe the bug**
A `GC` can no longer be created from an `Image` inside a thread on Windows. This used to work in older versions and still works under Linux. According to my understanding of the `GC` javadoc this is a valid use case, but I might be wrong about that.

In commit f809372 (see #62 and #127) [org.eclipse.swt.graphics.Image](https://github.com/eclipse-platform/eclipse.platform.swt/blob/f80937230f0caf83f0c38fd6536654b301b8934d/bundles/org.eclipse.swt/Eclipse%20SWT/win32/org/eclipse/swt/graphics/Image.java), line 2156
`data.font = device.systemFont;`
was changed to
`data.font = Font.win32_new(device.getSystemFont(), DPIUtil.getNativeDeviceZoom());`

`device.getSystemFont()` leads to calling `Display::checkDevice()` which asserts that the current thread is the display thread, which is not the case if the GC is created from another thread.

**To Reproduce**
```Java
import org.eclipse.swt.graphics.GC;
import org.eclipse.swt.graphics.Image;
import org.eclipse.swt.widgets.Display;

public class Test {

	public static void main(String[] args) {
		new Display();

		Thread thread = new Thread(() -> {
			Image image = new Image(null, 100, 100);
			GC gc = new GC(image); // <-- throws SWTException
			gc.dispose();
			image.dispose();
		});
		thread.start();

		try {
			thread.join();
		} catch (InterruptedException e) {
			e.printStackTrace();
		}
	}
}
```

**Expected behavior**
According to the JavaDoc of `GC`, I'd expect no exception, as long as the drawable (which is an `Image`) is created in the same thread.

**Stack Trace**
```
Exception in thread "Thread-0" org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.widgets.Display.error(Display.java:1286)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:863)
	at org.eclipse.swt.widgets.Display.getPrimaryMonitor(Display.java:2245)
	at org.eclipse.swt.widgets.Display.getSystemFont(Display.java:2459)
	at org.eclipse.swt.graphics.Image.internal_new_GC(Image.java:2156)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:171)
	at org.eclipse.swt.graphics.GC.<init>(GC.java:135)
	at package.Test.lambda$0(Test.java:14)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```

**Environment:**
- [ ] All OS
- [x] Windows
- [ ] Linux
- [ ] macOS

**Comment by akurtakov** [comment]
@akoch-yatta @HeikoKlare Would you please look into this one?

**Comment by akoch-yatta** [comment]
@akurtakov I'll have a look

**Comment by akoch-yatta** [comment]
@ddscharfe thank you for the analysis. I'll agree on it and will see, how I can resolve that issue

**Comment by akoch-yatta** [comment]
Created PR #1289 for this issue
