### ISSUE TITLE
Test_org_eclipse_swt_browser_Browser fails in IBuilds

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.swt#1455]
Test_org_eclipse_swt_browser_Browser
for example:

```
java.lang.IllegalArgumentException: Illegal character in opaque part at index 2: C:\Users\genie.releng\workspace\AutomatedTests\ep434I-unit-win32-java17/workarea/I20240908-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.600.v20240905-0755/data/testWebsiteWithTitle.html
at java.base/java.net.URI.create(URI.java:906)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.getValidUrl(Test_org_eclipse_swt_browser_Browser.java:568)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.test_isLocationForCustomText_isSetUrlNotCustomTextUrl(Test_org_eclipse_swt_browser_Browser.java:580)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.eclipse.test.TracingSuite.runChild(TracingSuite.java:279)Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 2: C:\Users\genie.releng\workspace\AutomatedTests\ep434I-unit-win32-java17/workarea/I20240908-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.600.v20240905-0755/data/testWebsiteWithTitle.html
at java.base/java.net.URI$Parser.fail(URI.java:2974)
at java.base/java.net.URI$Parser.checkChars(URI.java:3145)
at java.base/java.net.URI$Parser.parse(URI.java:3181)
at java.base/java.net.URI.<init>(URI.java:623)
at java.base/java.net.URI.create(URI.java:904)... 4 more
```
https://download.eclipse.org/eclipse/downloads/drops4/I20240908-1800/testresults/html/org.eclipse.swt.tests_ep434I-unit-win32-java17_win32.win32.x86_64_17.html

(but also other OS)

probably since recent https://github.com/eclipse-platform/eclipse.platform.swt/pull/1409
@HeikoKlare  @amartya4256

**Comment by HeikoKlare** [comment]
Definitely introduced by #1409, I will have a look.

Note that the failures on Linux and MacOS are different (both w.r.t. to assertion/message as well as regarding the cause):
```
Url is wrongly considered Custom Text Url expected:<file:///Users/genie.releng/workspace/AutomatedTests/ep434I-unit-mac64-java17/workarea/I20240908-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.600.v20240905-0755/data/testWebsiteWithTitle.html> but was:</Users/genie.releng/workspace/AutomatedTests/ep434I-unit-mac64-java17/workarea/I20240908-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.600.v20240905-0755/data/testWebsiteWithTitle.html>

java.lang.AssertionError: Url is wrongly considered Custom Text Url expected:<file:///Users/genie.releng/workspace/AutomatedTests/ep434I-unit-mac64-java17/workarea/I20240908-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.600.v20240905-0755/data/testWebsiteWithTitle.html> but was:</Users/genie.releng/workspace/AutomatedTests/ep434I-unit-mac64-java17/workarea/I20240908-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.600.v20240905-0755/data/testWebsiteWithTitle.html>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:120)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.test_isLocationForCustomText_isSetUrlNotCustomTextUrlAfterSetText(Test_org_eclipse_swt_browser_Browser.java:543)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.eclipse.test.TracingSuite.runChild(TracingSuite.java:279)
```

**Comment by HeikoKlare** [comment]
Validated that tests properly work now with today's I-Build: https://download.eclipse.org/eclipse/downloads/drops4/I20240911-1800/testResults.php

**Comment by jukzi** [comment]
todays test results look like the test has not been executed at all

**Comment by merks** [comment]
Yes, there are a lot of tests that failed to start that will hopefully be fixed by this:

https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2336

**Comment by HeikoKlare** [comment]
> todays test results look like the test has not been executed at all

Are you sure? I can see them in the tests results, e.g.:

https://download.eclipse.org/eclipse/downloads/drops4/I20240911-1800/testresults/html/org.eclipse.swt.tests_ep434I-unit-mac64-java17_macosx.cocoa.x86_64_17.html
![image](https://github.com/user-attachments/assets/1b990175-cbdf-49fe-9291-a4cb56ccfdc7)
https://download.eclipse.org/eclipse/downloads/drops4/I20240911-1800/testresults/html/org.eclipse.swt.tests_ep434I-unit-win32-java17_win32.win32.x86_64_17.html
![image](https://github.com/user-attachments/assets/d499cf0b-1af1-4db4-b24c-6ba975c4791a)
