### ISSUE TITLE
Random "Too many leaked file descriptors" in Test_org_eclipse_swt_browser_Browser

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.swt#1523]
for example

```
java.lang.AssertionError: Too many (62) leaked file descriptors: [/home/jenkins/.m2/repository/biz/aQute/bnd/biz.aQute.repository/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/biz/aQute/bnd/biz.aQute.repository/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/biz/aQute/bnd/biz.aQute.resolve/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/biz/aQute/bnd/biz.aQute.resolve/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/_remote.repositories, /home/jenkins/.m2/repository/commons-beanutils/commons-beanutils/1.9.4/_remote.repositories, /home/jenkins/.m2/repository/commons-collections/commons-collections/3.2.2/_remote.repositories, /home/jenkins/.m2/repository/commons-collections/commons-collections/3.2.2/_remote.repositories, /home/jenkins/.m2/repository/commons-collections/commons-collections/3.2.2/commons-collections-3.2.2-sources.jar, /home/jenkins/.m2/repository/org/apache/felix/org.apache.felix.gogo.command/1.1.2/_remote.repositories, /home/jenkins/.m2/repository/org/apache/felix/org.apache.felix.gogo.command/1.1.2/_remote.repositories, /home/jenkins/.m2/repository/org/apache/felix/org.apache.felix.gogo.runtime/1.1.6/_remote.repositories, /home/jenkins/.m2/repository/org/apache/felix/org.apache.felix.gogo.runtime/1.1.6/_remote.repositories, /home/jenkins/.m2/repository/org/apache/felix/org.apache.felix.gogo.shell/1.1.4/_remote.repositories, /home/jenkins/.m2/repository/org/apache/felix/org.apache.felix.gogo.shell/1.1.4/_remote.repositories, /home/jenkins/.m2/repository/org/apache/felix/org.apache.felix.scr/2.2.12/_remote.repositories, /home/jenkins/.m2/repository/org/apache/felix/org.apache.felix.scr/2.2.12/_remote.repositories, /home/jenkins/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/_remote.repositories, /home/jenkins/.m2/repository/org/apiguardian/apiguardian-api/1.1.2/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/bndtools.api/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/bndtools.api/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/bndtools.jareditor/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/bndtools.jareditor/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.headless.build.manager/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.headless.build.manager/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.headless.build.plugin.gradle/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.headless.build.plugin.gradle/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.templates.template/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.templates.template/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.templating/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.templating/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.versioncontrol.ignores.manager/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.versioncontrol.ignores.manager/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.versioncontrol.ignores.plugin.git/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/bndtools/org.bndtools.versioncontrol.ignores.plugin.git/7.0.0/_remote.repositories, /home/jenkins/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/jupiter/junit-jupiter-api/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/jupiter/junit-jupiter-engine/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/jupiter/junit-jupiter-migrationsupport/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/jupiter/junit-jupiter-migrationsupport/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/jupiter/junit-jupiter-params/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-commons/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-commons/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-engine/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-engine/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-launcher/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-launcher/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-runner/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-runner/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-suite-api/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-suite-api/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-suite-commons/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-suite-commons/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-suite-engine/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/platform/junit-platform-suite-engine/1.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/vintage/junit-vintage-engine/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/junit/vintage/junit-vintage-engine/5.11.2/_remote.repositories, /home/jenkins/.m2/repository/org/opentest4j/opentest4j/1.3.0/_remote.repositories, /home/jenkins/.m2/repository/org/opentest4j/opentest4j/1.3.0/_remote.repositories, /tmp/tycho_wrapped_source16950920715667920006.jar, socket:[760894302]]
	at org.junit.Assert.fail(Assert.java:89)
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.reportOpenedDescriptors(Test_org_eclipse_swt_browser_Browser.java:245)
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.tearDown(Test_org_eclipse_swt_browser_Browser.java:220)
```
https://ci.eclipse.org/releng/job/eclipse.platform.swt/job/PR-1522/1/testReport/

**Comment by fedejeanne** [comment]
It seems to fail for Mac too:

```
Too many (64) leaked file descriptors: [/home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/bin/org/eclipse/swt/internal/cocoa/NSSavePanel.class, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org/eclipse, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org/eclipse, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org/eclipse/swt, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org/eclipse/swt, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org/eclipse/swt/internal, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org/eclipse/swt/internal, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org/eclipse/swt/internal/cocoa, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org/eclipse/swt/internal/cocoa, /home/jenkins/agent/workspace/eclipse.platform.swt_PR-1677/eclipse.platform.swt/binaries/org.eclipse.swt.cocoa.macosx.aarch64/target/classes/org/eclipse/swt/internal/cocoa/NSSavePanel.class, /proc/407/cgroup, /proc/407/statm, /proc/meminfo, /proc/zoneinfo, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.core.runtime/.extraData.5, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.core.runtime/.mainData.5, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.core.runtime/.manager/.tmp413.instance, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.equinox.app/.manager/.tmp414.instance, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/100/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/102/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/110/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/12/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/123/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/124/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/129/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/134/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/135/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/138/0/bundleFile/pdebuild.jar, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/140/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/16/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/17/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/18/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/19/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/36/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/37/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/39/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/40/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/50/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/51/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/56/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/57/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/60/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/63/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/66/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/68/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/75/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/79/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/81/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/85/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/86/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/88/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/9/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/90/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/91/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/94/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/configuration/org.eclipse.osgi/98/0/bundleFile, /tmp/eclipseWorkspace8584303363514347623/data/.metadata/.plugins/org.eclipse.pde.core/.extensions/.manager/.tmp416.instance, /tmp/surefire-1002310000/stdout-20241220203007480_18deferred, socket:[367608482], socket:[367613187]]
```

Happened in #1677
