### ISSUE TITLE
Just updated Eclipse, and it will no longer start

### ISSUE THREAD

**Issue by JMarkMurphy** [eclipse-platform/eclipse.platform.swt#1544]
**Describe the bug**
I just updated Eclipse, and now it will not start here is the log file:

    !SESSION 2024-10-17 15:04:54.713 -----------------------------------------------
    eclipse.buildId=4.33.0.20240905-0613
    java.version=21.0.4
    java.vendor=Eclipse Adoptium
    BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en_US
    Framework arguments:  -product org.eclipse.epp.package.jee.product
    Command-line arguments:  -os win32 -ws win32 -arch x86_64 -product org.eclipse.epp.package.jee.product

    !ENTRY ch.qos.logback.classic 1 0 2024-10-17 15:04:58.261
    !MESSAGE Activated before the state location was initialized. Retry after the state location is initialized.

    !ENTRY org.eclipse.osgi 4 0 2024-10-17 15:04:58.788
    !MESSAGE Application error
    !STACK 1
    java.lang.UnsatisfiedLinkError: Could not load SWT library. Reasons:
        C:\eclipse\configuration\org.eclipse.osgi\1960\0\.cp\swt-win32-4966r5.dll: The specified procedure could not be found
	    no swt-win32 in java.library.path: C:\eclipse;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Eclipse Adoptium\jdk-11.0.19.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;e:\batch;C:\Program Files\Microsoft SQL Server Migration Assistant for Access\bin\;C:\Users\mmurphy\AppData\Local\Microsoft\WindowsApps;C:\Users\mmurphy\.dotnet\tools;.
	    no swt in java.library.path: C:\eclipse;C:\Windows\Sun\Java\bin;C:\Windows\system32;C:\Windows;C:\Program Files\Eclipse Adoptium\jdk-11.0.19.7-hotspot\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\dotnet\;C:\Program Files\TortoiseGit\bin;C:\Program Files\Git\cmd;e:\batch;C:\Program Files\Microsoft SQL Server Migration Assistant for Access\bin\;C:\Users\mmurphy\AppData\Local\Microsoft\WindowsApps;C:\Users\mmurphy\.dotnet\tools;.
	    C:\Users\mmurphy\.swt\lib\win32\x86_64\swt-win32-4966r5.dll: The specified procedure could not be found
	    Can't load library: C:\Users\mmurphy\.swt\lib\win32\x86_64\swt-win32.dll
	    Can't load library: C:\Users\mmurphy\.swt\lib\win32\x86_64\swt.dll
	    C:\Users\mmurphy\.swt\lib\win32\x86_64\swt-win32-4966r5.dll: The specified procedure could not be found

	    at org.eclipse.swt.internal.Library.loadLibrary(Library.java:345)
	    at org.eclipse.swt.internal.Library.loadLibrary(Library.java:254)
	    at org.eclipse.swt.internal.C.<clinit>(C.java:19)
	    at org.eclipse.swt.internal.win32.STARTUPINFO.<clinit>(STARTUPINFO.java:42)
	    at org.eclipse.swt.widgets.Display.<clinit>(Display.java:150)
	    at org.eclipse.ui.internal.Workbench.createDisplay(Workbench.java:721)
	    at org.eclipse.ui.PlatformUI.createDisplay(PlatformUI.java:185)
	    at org.eclipse.ui.internal.ide.application.IDEApplication.createDisplay(IDEApplication.java:182)
	    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:125)
	    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	    at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	    at org.eclipse.equinox.launcher.Main.run(Main.java:1481)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [X] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
  Windows 10

3. JRE/JDK version
I don't know really, the log reports Java 21 but I have Java 11 in my library path. Do I have to upgrade to Java 21 manually?

**Comment by merks** [comment]
Can you provide more details about exactly which version of Windows is involved?  The problem sounds familiar and related to quite old versions of Windows.

**Comment by JMarkMurphy** [comment]
Version 22H2 (OS Build 19045.5011)

Unfortunately this is a corporate laptop, and Windows updates are tightly controlled, so the version could be quite old.

**Comment by JMarkMurphy** [comment]
I would be happy with a work around.

**Comment by jukzi** [comment]
`Windows Server 2016 not supported` https://stackoverflow.com/a/79014382

**Comment by jukzi** [comment]
duplicates https://github.com/eclipse-platform/eclipse.platform.swt/issues/1500
