### ISSUE TITLE
Splash screen is not rendered on Wayland

### ISSUE THREAD

**Issue by Mailaender** [eclipse-platform/eclipse.platform.swt#1609]
I can reproduce this with both ChemClipse and the Eclipse IDE version 4.33.0 itself. Not sure why this happens or where to start fixing this. All the other images in the application load just fine.

```
org.eclipse.swt.SWTException: Invalid image
	at org.eclipse.swt.SWT.error(SWT.java:4922)
	at org.eclipse.swt.SWT.error(SWT.java:4837)
	at org.eclipse.swt.SWT.error(SWT.java:4808)
	at org.eclipse.swt.graphics.ImageLoader.getImageDataArrayFromStream(ImageLoader.java:210)
	at org.eclipse.swt.graphics.ImageLoader.load(ImageLoader.java:164)
	at org.eclipse.swt.graphics.ImageDataLoader.load(ImageDataLoader.java:25)
	at org.eclipse.swt.graphics.ImageData.<init>(ImageData.java:334)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:526)
	at org.eclipse.ui.internal.Workbench.getImage(Workbench.java:856)
	at org.eclipse.ui.internal.Workbench.loadSplashScreenImage(Workbench.java:847)
	at org.eclipse.ui.internal.Workbench$3.run(Workbench.java:766)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:47)
	at org.eclipse.ui.internal.Workbench.createSplashWrapper(Workbench.java:823)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:607)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.chemclipse.rcp.app.ui.internal.support.ApplicationSupportDefault.start(ApplicationSupportDefault.java:25)
	at org.eclipse.chemclipse.rcp.app.ui.Application.start(Application.java:27)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
```

**Comment by akurtakov** [comment]
OK, I think I got it. Splash screen is BMP image (which is missing in your list). This seems to be Fedora so would you please install gdk-pixbuf2-modules-extra (contains the BMP support) and report whether this fixes the issue.
There have been discussions (can't find the link now) about Gnome dropping support for many "legacy" image formats so it's worth trying to report to Fedora that gdk-pixbuf2-modules-extra is not installed by default but again it is probably a deliberate choice. If that's the case Eclipse would have to look for another image format for the splash as that would probably go to other distros too.

**Comment by akurtakov** [comment]
https://github.com/eclipse-platform/eclipse.platform.swt/issues/1307 has the background story.

**Comment by Mailaender** [comment]
I see installing `gdk-pixbuf2-modules-extra` indeed does fix it. A proper fix would probably to add a dependency but I am not sure how to add that to @flatpak or tarball installation. Went with a FAQ instead: https://fedoraproject.org/wiki/Eclipse#Troubleshooting
