### ISSUE TITLE
[mac] Test_org_eclipse_swt_browser_Browser.test_execute_and_closeListener is flaky

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.swt#1625]
Failed for **Mac** in [this build](https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/12048486168/job/33593211024?pr=1603) of #1603 

```java
Error:  org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.test_execute_and_closeListener[browser flags: 0] -- Time elapsed: 18.70 s <<< FAILURE!
java.lang.AssertionError: Either browser.execute() did not work (if you still see the html page) or closeListener Was not triggered if browser looks disposed, but test still fails.
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.test_execute_and_closeListener(Test_org_eclipse_swt_browser_Browser.java:1805)
...
```

**Comment by HeikoKlare** [comment]
I have not seen this test failing for quite a while.
