### ISSUE TITLE
Edge: Strange error when disposing a new Browser instance immediately after creating it

### ISSUE THREAD

**Issue by merks** [eclipse-platform/eclipse.platform.swt#1664]
When using the latest target platform,  starting the installer logs exceptions like this:
```
!MESSAGE No more handles [0x8007139f]
!STACK 0
org.eclipse.swt.SWTError: No more handles [0x8007139f]
	at org.eclipse.swt.SWT.error(SWT.java:4962)
	at org.eclipse.swt.browser.Edge.error(Edge.java:225)
	at org.eclipse.swt.browser.Edge.setupBrowser(Edge.java:600)
	at org.eclipse.swt.browser.Edge.lambda$10(Edge.java:580)
	at org.eclipse.swt.browser.Edge.lambda$5(Edge.java:232)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3693)
	at org.eclipse.oomph.setup.internal.installer.Installer.runEventLoop(Installer.java:382)
	at org.eclipse.oomph.setup.internal.installer.SimpleInstallerDialog.runEventLoop(SimpleInstallerDialog.java:1001)
	at org.eclipse.oomph.setup.internal.installer.AbstractSimpleDialog.show(AbstractSimpleDialog.java:195)
	at org.eclipse.oomph.setup.internal.installer.InstallerApplication.run(InstallerApplication.java:295)
	at org.eclipse.oomph.setup.internal.installer.InstallerApplication.start(InstallerApplication.java:401)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:668)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:605)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1481)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1454)
```
I was messing around with the code that tests whether a browser can be created:
```
  public static synchronized boolean isBrowserAvailable()
  {
    if (browserAvailable == null)
    {
      syncExec(new Runnable()
      {
        @Override
        public void run()
        {
          Shell shell = null;

          try
          {
            shell = new Shell();
            new Browser(shell, SWT.NONE);
            while (shell.getDisplay().readAndDispatch())
            {
            }
            browserAvailable = true;
          }
          catch (SWTError ex)
          {
            browserAvailable = false;
          }
          finally
          {
            try
            {
              shell.dispose();
            }
            catch (Exception ex)
            {
              // Ignore.
            }
          }
        }
      });
    }

    return browserAvailable;
  }
```
Adding the `while (shell.getDisplay().readAndDispatch())` makes the problem go away, so I think if one creates a browser and disposes it, there are maybe still events processed later for that browser that fail in this strange way.  Does anything guard that you aren't trying to process something for a disposed Edge instance?

**Comment by merks** [comment]
I'm also seeing this in my console with the installer and when launching an IDE upon termination.
```
[1216/090005.320:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1411
```

**Comment by Phillipus** [comment]
> `[1216/090005.320:ERROR:window_impl.cc(121)] Failed to unregister class Chrome_WidgetWin_0. Error = 1411`

I've seen that for a long time using Edge in our RCP app.

And see https://github.com/eclipse-platform/eclipse.platform.swt/issues/1498

**Comment by sratz** [comment]
The error handling in https://github.com/eclipse-platform/eclipse.platform.swt/blob/1ced8a9ca11fe20047d988a0252a9045beeeb070/bundles/org.eclipse.swt/Eclipse%20SWT%20Browser/win32/org/eclipse/swt/browser/Edge.java#L586-L601 might not be sufficient.

In this case I think we are seeing _The creation will fail with `E_ABORT` if parentWindow` is destroyed before the creation is finished._ according to https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment#createcorewebview2controller.

Defaulting to `NO_MORE_HANDLES` as error code does not seem ideal to me in general.

**Comment by fedejeanne** [comment]
cc @amartya4256 , @akoch-yatta

**Comment by merks** [comment]
FYI, this workaround works okay:
```
  public static synchronized boolean isBrowserAvailable()
  {
    if (browserAvailable == null)
    {
      syncExec(new Runnable()
      {
        @Override
        public void run()
        {
          try
          {
            Shell shell = new Shell();
            shell.getDisplay().asyncExec(() -> {
              try
              {
                shell.dispose();
              }
              catch (Exception ex)
              {
                // Ignore.
              }
            });

            new Browser(shell, SWT.NONE);
            browserAvailable = true;
          }
          catch (SWTError ex)
          {
            browserAvailable = false;
          }
        }
      });
    }

    return browserAvailable;
  }
```
The workaround above broke other logic that relied on posting events for delays processing...

**Comment by fedejeanne** [comment]
This error shows up also in the builds in `master` (GH Actions) _e.g._ right after merging #1673 

![image](https://github.com/user-attachments/assets/b19fc5ba-2590-4aaf-b6cf-b57c7bf89233)

I added it to our board: https://github.com/vi-eclipse/Eclipse-Platform/issues/163

**Comment by HeikoKlare** [comment]
> In this case I think we are seeing _'The creation will fail with `E_ABORT` if `parentWindow` is destroyed before the creation is finished.'_ according to https://learn.microsoft.com/en-us/microsoft-edge/webview2/reference/win32/icorewebview2environment#createcorewebview2controller.

I agree that we need to implement that case. I actually have a branch lying around to implement this but forgot to propose a PR from it so far. I will do that today.

Still, that does not seem to be the issue that we face here. The error code for an aborted operation is `0x80004004`.
The error code we have here is `0x8007139f`, which means: `The group or resource is not in the correct state to perform the requested operation`.
According to a quick web search, this may arise when there is still a WebView process running for the same data folder for which you try to create a new WebView environment.

**Comment by amartya4256** [comment]
Found this related to the error code 139f here: https://github.com/MicrosoftEdge/WebView2Feedback/issues/2495

**Comment by amartya4256** [comment]
@merks Is there anyway I can reproduce it locally? I can't manage to reproduce the exception using the SDK product.

**Comment by merks** [comment]
If you provision an IDE with both Oomph and SWT:

![image](https://github.com/user-attachments/assets/ec4fa5fd-aff4-4cce-ba36-c79f20f88b7e)

then you should be able to reproduce it there.  If the targlet task fails, just perform the setup tasks again.

You can go back to before this commit:

![image](https://github.com/user-attachments/assets/d2b0920a-a8bc-4737-926e-e66433ead33e)

But when I tried that, I can't reproduce the problem anymore now either.  So I'm not sure what commits all changed the behavior or what else might have changed...

In any case, the changes I made to avoid the problem are just fine, so I'm okay if this problem is simply closed because surely this must be come strange corner case.

**Comment by HeikoKlare** [comment]
Thank you, Ed! I cannot reproduce the issue with just starting the installer from the workspace either. I am only able to produce the issue when I start the installer with an explicitly changed Edge browser configuration while having an installer with the original Edge browser configuration running:
```
!ENTRY org.eclipse.oomph.setup.installer 4 0 2025-01-04 09:34:47.379
!MESSAGE No more handles [0x8007139f]
!STACK 0
org.eclipse.swt.SWTError: No more handles [0x8007139f]
	at org.eclipse.swt.SWT.error(SWT.java:4962)
	at org.eclipse.swt.browser.Edge.error(Edge.java:225)
	at org.eclipse.swt.browser.Edge.setupBrowser(Edge.java:601)
	at org.eclipse.swt.browser.Edge.lambda$10(Edge.java:581)
	at org.eclipse.swt.browser.Edge.lambda$5(Edge.java:232)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3693)
	at org.eclipse.oomph.setup.internal.installer.Installer.runEventLoop(Installer.java:382)
```

That is somehow "expected" as that's exactly the case where this error should be thrown. The data folder is, by default, placed in a subfolder of your AppData folder, named according to the Eclipse application. So for the installer, it is: "C:\Users\YOUR_NAME\AppData\Local\Eclipse Installer"

So assuming that there was actually another Eclipse application named "Eclipse Installer" running at the same time when you faced the issue, the question remains why that one had a different configuration of the Edge browser. I could imagine that it may be because the other application was running with a different localization. Or maybe you had some other installer based on a different build (using some other configuration) running at the same time.

No matter which configuration was different, starting another Edge instance with a different configuration on the same data folder should actually be the one reason specified by Microsoft causing that error. So for me the question is whether this was really a corner case or whether it is something that may happen more often and requires some improvement. In "usual" Eclipse applications (with a workspace) this will not happen because the data directory is placed within the workspace metadata folder instead of the AppData folder. On solution to avoid that multiple applications having the same name use the same Edge data folder might be to of a different identifier used to create that folder withint the AppData folder, such as encoding the file system path to the application or the like.

**Comment by merks** [comment]
This is no longer a problem.
