### ISSUE TITLE
[Win][Edge]Test_org_eclipse_swt_browser_Browser.test_setUrl_local fails for Edge

### ISSUE THREAD

**Issue by fedejeanne** [eclipse-platform/eclipse.platform.swt#1670]
**Describe the bug**
The test `Test_org_eclipse_swt_browser_Browser.test_setUrl_local` fails for the **Edge** browser in the I-BUILDs and for both IE and Edge when run locally. 

### Stack trace (I-BUILD)
```java
Multiple Failures (2 failures) org.junit.ComparisonFailure: Test log: PLUGIN_PATH: C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java21/workarea/I20241216-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.700.v20241216-1631 URL: C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java21/workarea/I20241216-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.700.v20241216-1631/data/testWebsiteWithTitle.html TitleListener fired expected:<[Website Title]> but was:<[c]> java.lang.RuntimeException: AwtScreenshot VM finished with exit code 1: Exception in thread "main" java.awt.AWTError: no screen devices at java.desktop/sun.awt.Win32GraphicsEnvironment.getDefaultScreenDevice(Win32GraphicsEnvironment.java:101) at java.desktop/java.awt.Robot.<init>(Robot.java:135) at org.eclipse.test.AwtScreenshot.main(AwtScreenshot.java:43)

org.opentest4j.MultipleFailuresError: Multiple Failures (2 failures)
org.junit.ComparisonFailure:
Test log:
PLUGIN_PATH: C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java21/workarea/I20241216-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.700.v20241216-1631
URL: C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java21/workarea/I20241216-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.700.v20241216-1631/data/testWebsiteWithTitle.html
TitleListener fired expected:<[Website Title]> but was:<[c]>
java.lang.RuntimeException: AwtScreenshot VM finished with exit code 1:
Exception in thread "main" java.awt.AWTError: no screen devices
at java.desktop/sun.awt.Win32GraphicsEnvironment.getDefaultScreenDevice(Win32GraphicsEnvironment.java:101)
at java.desktop/java.awt.Robot.<init>(Robot.java:135)
at org.eclipse.test.AwtScreenshot.main(AwtScreenshot.java:43)

at org.eclipse.test.TracingSuite$TracingRunNotifier.fireTestFinished(TracingSuite.java:176)
at org.eclipse.test.TracingSuite.runChild(TracingSuite.java:287)
Suppressed: org.junit.ComparisonFailure:
Test log:
PLUGIN_PATH: C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java21/workarea/I20241216-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.700.v20241216-1631
URL: C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java21/workarea/I20241216-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.700.v20241216-1631/data/testWebsiteWithTitle.html
TitleListener fired expected:<[Website Title]> but was:<[c]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.validateTitleChanged(Test_org_eclipse_swt_browser_Browser.java:1262)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.test_setUrl_local(Test_org_eclipse_swt_browser_Browser.java:1188)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
... 1 more
Suppressed: java.lang.RuntimeException: AwtScreenshot VM finished with exit code 1:
Exception in thread "main" java.awt.AWTError: no screen devices
at java.desktop/sun.awt.Win32GraphicsEnvironment.getDefaultScreenDevice(Win32GraphicsEnvironment.java:101)
at java.desktop/java.awt.Robot.<init>(Robot.java:135)
at org.eclipse.test.AwtScreenshot.main(AwtScreenshot.java:43)

at org.eclipse.test.AwtScreenshot.dumpAwtScreenshot(AwtScreenshot.java:113)
at org.eclipse.test.Screenshots.takeScreenshot(Screenshots.java:102)
at org.eclipse.test.Screenshots$ScreenshotOnFailure.failed(Screenshots.java:40)
... 1 more 
```

**To Reproduce**
- Let it run in the nightly I-BUILD or
- Run the test locally

**Expected behavior**
The test shouldn't fail

**Environment:**

- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

**Version since**
I-BUILD **I20241216-1800**, since the tests for Edge were activated (#672)

**Comment by HeikoKlare** [comment]
I am not sure how to locally reproduce the issue / test failure. In an I-Build, the SWT tests are executed as plugin tests (in an OSGi environment), with the plugin path to load resources from (in case of this test an HTML document) explicitly specified (via the `PLUGIN_PATH` environment variable).
Locally (and in GH actions builds), the SWT tests are executed as plain JUnit tests, in which resource resolution is done via the (single) classloader. In this case, the tests run fine, they succeed both in GH actions builds as well as locally.
When executing the test as plugin test locally, it will fail (expectedly) as it is not configured for this scenario: it will use the classloader to resolve the test resource (as the environment variable `PLUGIN_PATH` is unspecified) , but the resulting URL is unprocessable for the browser.

In addition, I do not see that this test fails for IE. At least in latest I-Build test results, that one succeeds, e.g., https://download.eclipse.org/eclipse/downloads/drops4/I20241230-1800/testresults/html/org.eclipse.swt.tests_ep435I-unit-win32-x86_64-java21_win32.win32.x86_64_21.html:
`test_setUrl_local[browser flags: 524,288]	Success`

**Comment by laeubi** [comment]
If I look at the output here:

```
PLUGIN_PATH: C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java21/workarea/I20241216-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.700.v20241216-1631
URL: C:\Users\genie.releng\workspace\AutomatedTests\ep435I-unit-win32-x86_64-java21/workarea/I20241216-1800/eclipse-testing/test-eclipse/eclipse/plugins/org.eclipse.swt.tests_3.107.700.v20241216-1631/data/testWebsiteWithTitle.html

```

for me it looks like there is an invalid assumption of how local path are converted into URI/URL and therfore one get `/` versus `\` what later on can not be processed. 

So maybe the test should simply account for this somehow before passing the URL along to the browser, extract it to a temp file or whatever seems suitable here.

**Comment by HeikoKlare** [comment]
Yes, that might be the reason. That would mean that IE was able to process such a URL while Edge is not. If that's the case, we may also just normalize the URL for Edge within the test.

I am not sure whether this `PLUGIN_PATH` variable is used anywhere else than in the SWT tests. And that one depends on specific ANT properties to be specified for each bundle (like `plugin-path`). So maybe getting rid of this could even simplify the I-Build-specific configuration for each test bundle.

**Comment by HeikoKlare** [comment]
Test was successfully executed in today's I-Build, so #1701 seems to have fixed the issue.
