### ISSUE TITLE
JDK crash on changing to classic theme

### ISSUE THREAD

**Issue by trancexpress** [eclipse-platform/eclipse.platform.swt#191]
[hs_err_pid49284.log](https://github.com/eclipse-platform/eclipse.platform.swt/files/8834743/hs_err_pid49284.log)

**Describe the bug**
While importing projects from the EGit repository, I went to general preferences -> appearance and tried to change to classic theme (my  system is on breeze dark theme, plasma KDE). Eclipse crashed. I've not tried to reproduce. 

**To Reproduce**
Doesn't seem readily reproducible. I was able to change the theme to classic on the next attempt.

**Expected behavior**
No crash.

**Screenshots**
https://user-images.githubusercontent.com/24752155/171923858-6ff226d7-461a-474d-8b27-8437e1185e5e.png

**Environment:**
- Select the platforms on which the behavior is seen.
[ ] All OS
[ ] Windows
[X] Linux
[ ] macOS
 
 - Additional OS info (e.g. OS version, Linux Desktop, etc)
 
ArchLinux

GTK 3.24.34-1

 - JRE/JDK version
 
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7)
OpenJDK 64-Bit Server VM (build 17.0.3+7, mixed mode)

**Version since**
Eclipse SDK
Version: 2022-06 (4.24)
Build id: I20220601-1800

**Comment by trancexpress** [comment]
```bt```:

(gdb) bt
#0  0x00007fe0eca8e36c in  () at /usr/lib/libc.so.6
#1  0x00007fe0eca3e838 in raise () at /usr/lib/libc.so.6
#2  0x00007fe0eca28535 in abort () at /usr/lib/libc.so.6
#3  0x00007fe0eb8505a8 in  () at /usr/lib/jvm/java-17-openjdk/lib/server/libjvm.so
#4  0x00007fe0ec51a3a5 in  () at /usr/lib/jvm/java-17-openjdk/lib/server/libjvm.so
#5  0x00007fe0ec51addf in  () at /usr/lib/jvm/java-17-openjdk/lib/server/libjvm.so
#6  0x00007fe0ec51ae12 in  () at /usr/lib/jvm/java-17-openjdk/lib/server/libjvm.so
#7  0x00007fe0ec3b9c06 in JVM_handle_linux_signal () at /usr/lib/jvm/java-17-openjdk/lib/server/libjvm.so
#8  0x00007fe0eca3e8e0 in <signal handler called> () at /usr/lib/libc.so.6
#9  0x00007fe0a06f5f95 in gtk_tree_model_get_valist () at /usr/lib/libgtk-3.so.0
#10 0x00007fe0a06f6328 in gtk_tree_model_get () at /usr/lib/libgtk-3.so.0
#11 0x00007fdf68246c6d in Java_org_eclipse_swt_internal_gtk_GTK_gtk_1tree_1model_1get__JJI_3JI ()
    at /data/eclipses/eclipseSDK_424_m20220601/configuration/org.eclipse.osgi/232/0/.cp/libswt-pi3-gtk-4952r11.so
#12 0x00007fe0d5690a8c in  ()
#13 0x00000000ffffffff in  ()
#14 0x00007fe0e6484970 in  ()
#15 0x00007fe0eb5fcd00 in  ()
#16 0x00007fe0ec1ce6a9 in  () at /usr/lib/jvm/java-17-openjdk/lib/server/libjvm.so
#17 0x00007fe0d59188a4 in  ()
#18 0x0000000606a62b58 in  ()
#19 0x0000000606101f30 in  ()
#20 0x00007fe0e4012f80 in  ()
#21 0x00007fdf318188d0 in  ()
#22 0x0000000000000000 in  ()

**Comment by akurtakov** [comment]
This sounds like a call to remove Classic theme to me. Without easy way to reproduce the crash I don't have high hopes for this one.

**Comment by iloveeclipse** [comment]
I would guess another KDE theme issue, we had lot of troubles with "oxygen" in the past.

**Comment by akurtakov** [comment]
As Classic theme is gone now -  Closing.
