### ISSUE TITLE
Support 16bpp palette images (such as 16bpp grayscale TIFF)

### ISSUE THREAD

**Issue by SyntevoAlex** [eclipse-platform/eclipse.platform.swt#232]
Currently, 16bpp palette images fail on Windows and on macOS.

On Windows, the image loads, but the colors are all wrong.
For example, here's the actual image:
![image](https://user-images.githubusercontent.com/45797751/176424992-68d21139-89b0-4f48-b9be-47d20560c101.png)
But SWT shows it this way:
![image](https://user-images.githubusercontent.com/45797751/176425191-d695a393-3fdd-4eea-96ae-be12111811d0.png)

On macOS, image fails to load with exception `SWT.ERROR_UNSUPPORTED_DEPTH`:
```
Caused by: org.eclipse.swt.SWTException: code=38
	at org.eclipse.swt.SWT.error(SourceFile:4918)
	at org.eclipse.swt.SWT.error(SourceFile:4833)
	at org.eclipse.swt.SWT.error(SourceFile:4804)
	at org.eclipse.swt.graphics.Image.createRepresentation(SourceFile:1002)
	at org.eclipse.swt.graphics.Image.init(SourceFile:1403)
	at org.eclipse.swt.graphics.Image.<init>(SourceFile:573)
```

**Comment by SyntevoAlex** [comment]
It should be possible to implement via GDI+. Looking at `Image.initNative()` however, it seems to also have some problems. So it's some work to be done, and unfortunately I can't volunteer for it at the moment.

**Comment by tmssngr** [comment]
It not only is an enhancement, but also a bug, because we've only got aware of it by a user who reported the crash.

**Comment by iloveeclipse** [comment]
org.eclipse.swt.tests.junit.Test_org_eclipse_swt_graphics_ImageData shows fails on both Mac/Linux builds in SDK tests:
https://download.eclipse.org/eclipse/downloads/drops4/I20220719-0530/testResults.php

@SyntevoAlex : could you please take a look?

**Comment by SyntevoAlex** [comment]
I understand that the error is this?
```
class org.eclipse.swt.graphics.ImageDataTestHelper tried to access method 'int org.eclipse.swt.graphics.ImageData.getByteOrder()' (org.eclipse.swt.graphics.ImageDataTestHelper is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1a78dacd; org.eclipse.swt.graphics.ImageData is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1af1347d)

java.lang.IllegalAccessError: class org.eclipse.swt.graphics.ImageDataTestHelper tried to access method 'int org.eclipse.swt.graphics.ImageData.getByteOrder()' (org.eclipse.swt.graphics.ImageDataTestHelper is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1a78dacd; org.eclipse.swt.graphics.ImageData is in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @1af1347d)
at org.eclipse.swt.graphics.ImageDataTestHelper.makeTestImageData(ImageDataTestHelper.java:154)
at org.eclipse.swt.graphics.ImageDataTestHelper$BlitTestInfo.<init>(ImageDataTestHelper.java:52)
at org.eclipse.swt.graphics.ImageDataTestHelper$BlitTestInfo.<init>(ImageDataTestHelper.java:74)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_graphics_ImageData.test_blit(Test_org_eclipse_swt_graphics_ImageData.java:71) 
```

Sounds like another problem when I try to access SWT's protected method from JUnit. Sigh, why does each bot run JUnit differently? On GitHub, it was due to #251. At the moment, I have no idea why is it unhappy. And I'm not sure I'm willing to spend time to diagnose this bot, going to be hard because my local JUnit runs differently.

**Comment by iloveeclipse** [comment]
> Any ideas on how to test SWT protected methods in spite of broken bots?

They are not broken, they simply run tests differently - one in OSGI based container, another in some Maven/Tycho environment. SDK test complains because Java doesn't allow package private access for classes that "looks like" coming from the same package, but loaded by different class loaders. Test bundle and SWT bundle classes **are** loaded by different classloaders, so error is correct.

I don't know why the test bundle is not a **fragment** of SWT - if it would be, it would be loaded by same class loader. So if that is not an option, one would need to some other way to access SWT code that shouldn't be public API - or make it API.

**Comment by SyntevoAlex** [comment]
Unfortunately I have no experience regarding OSGI containers and fragments. As for putting classes into foreign package to access protected methods, that's the official recommendation by JUnit - https://junit.org/junit4/faq.html#organize_1

**Comment by SyntevoAlex** [comment]
Why does it use different classloaders? Couldn't it just use one for both purposes?

**Comment by iloveeclipse** [comment]
Sure, in a non-modular world, where every class is loaded by same classloader the recommendation from JUnit guys works. But in Eclipse we use OSGI that separates bundles by loading classes from different classloaders, and that is nothing we can/will fix, it is a feature, not bug.

So if you don't see other possibility to access the code one need for tests, you could disable the test if it runs in OSGI container ( if ! Platform.isRunning()...).

**Comment by SyntevoAlex** [comment]
I don't mind disabling test in OSGI.

Unfortunately `Platform.isRunning()` is not available in SWT. Maybe test `System.getProperty("org.osgi.framework.vendor")` ? I just picked something relevant from https://download.eclipse.org/eclipse/downloads/drops4/I20220719-0530/testresults/xml/org.eclipse.swt.tests_ep425I-unit-mac64-java17_macosx.cocoa.x86_64_17.xml

**Comment by iloveeclipse** [comment]
> Unfortunately `Platform.isRunning()` is not available in SWT

Sure, but isn't that available in SWT *tests*? Usually tests have more dependencies. 
If not, I think one can check any SWT class classloader name - in Equinox it will be a different one, don't know the class name without IDE, but you can easily see it in debugger. Or just compare classloader instances that loaded test class and ImageData class - if they are different, the test won't work anyway.

**Comment by iloveeclipse** [comment]
See for example http://moi.vonos.net/java/osgi-classloaders/ about OSGI and class loading in OSGI container.

**Comment by SyntevoAlex** [comment]
> Sure, but isn't that available in SWT tests?

I don't see it anywhere in my project that includes SWT and SWT tests. My project is custom made though.

> Maybe test System.getProperty("org.osgi.framework.vendor") ?

Is this a bad approach?

**Comment by iloveeclipse** [comment]
> Is this a bad approach?

The test relies on the fact it is loaded by same classloader as the class under test, so why not add this self-documenting check? Testing for some system property will probably work too, but that is not so obvious I think. Also anyone can set the property for some obscure reason (to workaround some other issue).

**Comment by SyntevoAlex** [comment]
If you were the first to notice that eclipse.org fails tests, and I followed the idea to compare classloaders, #251 would not be discovered. Also, I take your word that OSGI can't be helped, but other build bots can probably be fixed in order to actually run the test. That's why it sounds better (to me) to only disable the test for OSGI and not compare classloaders.

Still, I admit that I'm not experienced in this area, so, considering this message, suggest me which of two approaches to take and I will do.

**Comment by SyntevoAlex** [comment]
Reading your link about OSGI, I agree that JUnit tests should be a fragment with `Fragment-Host: org.eclipse.swt`.
I found that platform specific SWT.jar already uses `Fragment-Host: org.eclipse.swt`.

I wandered in darkness for a few hours and didn't even find where does `MANIFEST.MF` come from for platform-specific SWT.jar. I also couldn't figure how to build it locally, which makes it even more complicated for me.

@akurtakov could you please help? I understand that you're the author of build scripts and I'm suffering in vain.

**Comment by akurtakov** [comment]
I'll try to look into it later today.

**Comment by akurtakov** [comment]
SWT tests are not using Tycho but rather plain Maven Surefire thus they don't run in OSGi container. I've made it a fragment as it seems the simplest solution and it doesn't break Maven build. Whether it fixes the I-build tests issue is to be seen tomorrow.

**Comment by akurtakov** [comment]
I had to revert the change making tests fragment due to the fact that swt implementation itself comes in the form of fragment and building one fragment with content from the other fragment is unsolvable issue. So swt.tests can not be fragment.

**Comment by SyntevoAlex** [comment]
I googled and found a possible workaround:
https://stackoverflow.com/questions/18171294

I understand that now that Bug 361901 is fixed (or is it?), this is the only thing that is needed for workaround:
```
extra.. = platform:/fragment/org.eclipse.swt.win32.win32.x86_64
```

Can it work here?

**Comment by akurtakov** [comment]
I run it locally and tests failed with:
```
Errors: 
[ERROR]   Test_org_eclipse_swt_graphics_ImageData.test_blit:69 » Security class "org.eclipse.swt.graphics.ImageDataTestHelper"'s signer information does not match signer information of other classes in the same package
[ERROR]   Test_org_eclipse_swt_graphics_ImageData.test_blit_MsbLsb:125 » Security class "org.eclipse.swt.graphics.ImageDataTestHelper$BlitTestInfo"'s signer information does not match signer information of other classes in the same package
[INFO] 
```
so maybe touching some bundle fragment so they are signed with same key will fix it?

**Comment by SyntevoAlex** [comment]
Do you run tests via maven? That sounds exactly like #251 to me. Hopefully when #251 is fixed, this will be fixed automatically.

I think that you should proceed with merging your part of the fix regarding fragments.

**Comment by SyntevoAlex** [comment]
To clarify, nether tests nor SWT shall be signed at all (with which key? Surely eclipse doesn't give its key in git repo?).
The problem you're seeing is because maven incorrectly downloads SWT from eclipse, which makes no sense.

**Comment by SyntevoAlex** [comment]
I even added a test to make sure that SWT is not signed, see #252

**Comment by SyntevoAlex** [comment]
Thought you were replying to https://github.com/eclipse-platform/eclipse.platform.swt/issues/232#issuecomment-1191820525
How about that workaround I found?
