### ISSUE TITLE
Test_org_eclipse_swt_graphics_TextLayout#test_getLineOffsets() JUnit failing on Windows.

### ISSUE THREAD

**Issue by niraj-modi** [eclipse-platform/eclipse.platform.swt#311]
**Describe the bug**
Failing JUnit on Windows since Eclipse IBuild: [I20220725-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220725-1800/testresults/html/org.eclipse.swt.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

**To Reproduce**
1. On Windows10
2. Run JUnit test from Test_org_eclipse_swt_graphics_TextLayout.java
3. Below JUnit failure is seen: Test_org_eclipse_swt_graphics_TextLayout#test_getLineOffsets() with below stack-trace:
------------------------------------------------------------------------------------------------------------------------------
array lengths differed, expected.length=3 actual.length=4; arrays first differed at element [1]; expected:<2> but was:<1>

array lengths differed, expected.length=3 actual.length=4; arrays first differed at element [1]; expected:<2> but was:<1>
at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:78)
at org.junit.internal.ComparisonCriteria.arrayEquals(ComparisonCriteria.java:28)
at org.junit.Assert.internalArrayEquals(Assert.java:534)
at org.junit.Assert.assertArrayEquals(Assert.java:418)
at org.junit.Assert.assertArrayEquals(Assert.java:429)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_graphics_TextLayout.test_getLineOffsets(Test_org_eclipse_swt_graphics_TextLayout.java:307)

**Expected behavior**
JUnit should pass on Windows as well.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

5. Additional OS info (e.g. OS version, Linux Desktop, etc)

6. JRE/JDK version
 
**Version since**
Since Eclipse IBuild: [I20220725-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20220725-1800/testresults/html/org.eclipse.swt.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html)

**Comment by niraj-modi** [comment]
All JUnits test passing on Windows in latest Eclipse I-Build:
https://download.eclipse.org/eclipse/downloads/drops4/I20220816-1800/testresults/html/org.eclipse.swt.tests_ep425I-unit-win32-java11_win32.win32.x86_64_11.html
