### ISSUE TITLE
Swt Exception: g_object_get_qdata returned unexpected index value, index: -1,

### ISSUE THREAD

**Issue by fabrizzle85** [eclipse-platform/eclipse.platform.swt#324]
**Describe the bug**
 SWTException : Return value not valid. g_object_get_qdata returned unexpected index value, index: -1, table size: 10240
org.eclipse.swt.SWTException: Return value not valid. g_object_get_qdata returned unexpected index value, index: -1, table size: 10240
	at org.eclipse.swt.SWT.error(SWT.java:4907)
	at org.eclipse.swt.widgets.Display.removeWidget(Display.java:5043)
	at org.eclipse.swt.widgets.Widget.deregister(Widget.java:493)
	at org.eclipse.swt.widgets.Control.deregister(Control.java:180)
	at org.eclipse.swt.widgets.Scrollable.deregister(Scrollable.java:203)
	at org.eclipse.swt.widgets.Composite.deregister(Composite.java:510)
	at org.eclipse.swt.widgets.Shell.deregister(Shell.java:3233)
	at org.eclipse.swt.widgets.Widget.releaseWidget(Widget.java:1364)
	at org.eclipse.swt.widgets.Control.releaseWidget(Control.java:4778)
	at org.eclipse.swt.widgets.Composite.releaseWidget(Composite.java:1576)
	at org.eclipse.swt.widgets.Decorations.releaseWidget(Decorations.java:525)
	at org.eclipse.swt.widgets.Shell.releaseWidget(Shell.java:3397)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1343)
	at org.eclipse.swt.widgets.Control.release(Control.java:4756)
	at org.eclipse.swt.widgets.Shell.releaseChildren(Shell.java:3378)
	at org.eclipse.swt.widgets.Widget.release(Widget.java:1331)
	at org.eclipse.swt.widgets.Control.release(Control.java:4756)
	at org.eclipse.swt.widgets.Widget.dispose(Widget.java:539)
	at org.eclipse.swt.widgets.Shell.dispose(Shell.java:3307)

**To Reproduce**
not reproducible

**Environment:**
Linux 
GTK-Version:  3.24.14
Theme: Kokodi (https://gitlab.xfce.org/Dridi/xfwm4/-/tree/master/themes/kokodi)

3. JRE/JDK version
JDK 11
 
**Version since**
SWT-Version: 3.120.0

**Same Bugs**
https://bugs.eclipse.org/bugs/show_bug.cgi?id=563390
https://bugs.eclipse.org/bugs/show_bug.cgi?id=541203
https://bugs.eclipse.org/bugs/show_bug.cgi?id=543210

**Comment by akurtakov** [comment]
Unfortunately without steps to reproduce and investigate what goes wrong there is nothing we can do. What I can recommend is trying to use another theme (preferably Adwaita)  and see whether you get the issue again. In the past such errors were theme related most of the time.

**Comment by SyntevoAlex** [comment]
Yes, please provide more details. Did it happen more than one time? Do you have at least unreliable steps to reproduce?

**Comment by SyntevoAlex** [comment]
I have checked bug report database for our product (not Eclipse) and there is a very small amount, but still not zero, of such exceptions in it. I checked 4 of these and all of them were for custom themes.

That said, if there are more or less clear steps to reproduce, I could give it a quick look. Otherwise, I guess it's not worth the effort.
