### ISSUE TITLE
SWT Application crashes on double click on coulmn divider to resize on Ubuntu (GTK) only

### ISSUE THREAD

**Issue by Aamir3T** [eclipse-platform/eclipse.platform.swt#330]
**Describe the bug**
SWT Application crashes if the user double click column divider to automatically resize.
This issue is reproducible on Ubuntu (GTK) only, it works correctly on Windows/Mac.
org.eclipse.jface.viewers.ColumnPixelData: (ColumnPixelData line 82)
-1 is passed to widthInPixels variable which causes following assertion to fail: 	Assert.isTrue(widthInPixels >= 0);

**To Reproduce**
Hover over the divider between the column name and double click when the cursor turns into double-arrow

**Expected behavior**
The coulmn width should be adjusted to max-length of cell content.

**Screenshots**
![image](https://user-images.githubusercontent.com/111754754/185977044-1b9d160a-8c7f-49b6-9ef8-9dc53e5eaad3.png)

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [x] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
 Ubuntu (20.04 and 22.04)

3. JRE/JDK version
 Java VM: OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (17.0.3+7, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, linux-aarch64)

**Version since**

**Workaround (or) Additional context**

Crash Details:
 A fatal error has been detected by the Java Runtime Environment:
 SIGSEGV (0xb) at pc=0x0000ffff5ca5424c, pid=443582, tid=443583
 Problematic frame:
 C  [libgtk-3.so.0+0x2bc24c]  gtk_range_get_adjustment+0x1c
Logs:
[Issue log1.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/9396053/Issue.log1.txt)

[Method Stack.txt](https://github.com/eclipse-platform/eclipse.platform.swt/files/9396166/Method.Stack.txt)

**Comment by Phillipus** [comment]
I can confirm this in our RCP app:

```
!ENTRY org.eclipse.ui 4 0 2022-08-22 18:40:06.743
!MESSAGE Unhandled event loop exception
!STACK 0
org.eclipse.core.runtime.AssertionFailedException: assertion failed: 
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:113)
	at org.eclipse.core.runtime.Assert.isTrue(Assert.java:99)
	at org.eclipse.jface.viewers.ColumnPixelData.<init>(ColumnPixelData.java:81)
	at org.eclipse.jface.viewers.ColumnPixelData.<init>(ColumnPixelData.java:51)
	at org.eclipse.jface.layout.TreeColumnLayout.updateColumnData(TreeColumnLayout.java:144)
	at org.eclipse.jface.layout.AbstractColumnLayout.lambda$0(AbstractColumnLayout.java:76)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5795)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1529)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1555)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1534)
	at org.eclipse.swt.widgets.TreeColumn.gtk_size_allocate(TreeColumn.java:425)
	at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:2445)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:6115)
	at org.eclipse.swt.internal.gtk3.GTK3.gtk_main_iteration_do(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4474)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at com.archimatetool.editor.Application.start(Application.java:81)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**Comment by Phillipus** [comment]
Here's a Snippet to test it:

<details>
<summary>Click to reveal code...</summary>

```java
import org.eclipse.jface.layout.TreeColumnLayout;
import org.eclipse.jface.viewers.CellLabelProvider;
import org.eclipse.jface.viewers.ColumnWeightData;
import org.eclipse.jface.viewers.ITreeContentProvider;
import org.eclipse.jface.viewers.TreeViewer;
import org.eclipse.jface.viewers.TreeViewerColumn;
import org.eclipse.jface.viewers.ViewerCell;
import org.eclipse.swt.SWT;
import org.eclipse.swt.layout.GridData;
import org.eclipse.swt.layout.GridLayout;
import org.eclipse.swt.widgets.Composite;
import org.eclipse.swt.widgets.Display;
import org.eclipse.swt.widgets.Shell;

public class TreeColumnTest {

    public static void main(String[] args) {
        Display display = new Display();
        Shell shell = new Shell(display);
        shell.setText("Tree Columns");
        shell.setSize(600, 400);
        shell.setLayout(new GridLayout(1, false));
        
        Composite treeComposite = new Composite(shell, SWT.BORDER);
        treeComposite.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true));
        TreeColumnLayout layout = new TreeColumnLayout();
        treeComposite.setLayout(layout);
        
        final TreeViewer tv = new TreeViewer(treeComposite, SWT.H_SCROLL | SWT.V_SCROLL | SWT.FULL_SELECTION);

        TreeViewerColumn column1 = new TreeViewerColumn(tv, SWT.NONE, 0);
        column1.getColumn().setText("c 1");
        layout.setColumnData(column1.getColumn(), new ColumnWeightData(33, true));
        
        TreeViewerColumn column2 = new TreeViewerColumn(tv, SWT.NONE, 1);
        column2.getColumn().setText("c 2");
        layout.setColumnData(column2.getColumn(), new ColumnWeightData(33, true));

        TreeViewerColumn column3 = new TreeViewerColumn(tv, SWT.NONE, 2);
        column3.getColumn().setText("c 3");
        column3.getColumn().setMoveable(true);
        layout.setColumnData(column3.getColumn(), new ColumnWeightData(33, true));

        tv.setContentProvider(new MyContentProvider());
        tv.setLabelProvider(new MyLabelProvider());
        
        tv.getTree().setHeaderVisible(true);
        tv.getTree().setLinesVisible(true);
        
        tv.setInput("");

        shell.open();
        
        while(!shell.isDisposed()) {
            if(!display.readAndDispatch()) display.sleep();
        }
        
        display.dispose();
    }
    
    static class MyContentProvider implements ITreeContentProvider {
        @Override
        public Object[] getElements(Object inputElement) {
            return new Object[] {"One", "Two", "Three"};
        }

        @Override
        public Object[] getChildren(Object parentElement) {
            return new Object[] {"Hello", "There"};
        }

        @Override
        public Object getParent(Object element) {
            return null;
        }

        @Override
        public boolean hasChildren(Object element) {
            return true;
        }
    }
    
    static class MyLabelProvider extends CellLabelProvider {
        @Override
        public void update(ViewerCell cell) {
            String text = (String)cell.getElement();
            cell.setText(text);
        }
    }
}
```

</details>

**Comment by Aamir3T** [comment]
Hi Team,
Do we have any estimate on the timeline?
When can we expect a fix?
Regards,
Aamir

**Comment by wimjongman** [comment]
> Hi Team, Do we have any estimate on the timeline? When can we expect a fix? Regards, Aamir

Aamir, can you make a patch for it?

**Comment by Aamir3T** [comment]
@wimjongman 
No, unfortunately I cannot create a patch for it.
The issue is specific to GTK and I don't have knowledge of it.
I have attached the method call stack for the issue.

**Comment by akurtakov** [comment]
@jasonhy-wang Would you please look into this one?

**Comment by SyntevoAlex** [comment]
Reproducible with an SWT snippet

```
final Display display = new Display();
final Shell shell = new Shell(display);
shell.setLayout (new GridLayout (1, true));

Tree tree = new Tree(shell, 0);
tree.setLayoutData(new GridData(SWT.FILL, SWT.FILL, true, true));
tree.setHeaderVisible(true);

for (int i = 0; i < 2; i++) {
	TreeColumn column = new TreeColumn(tree, 0);
	column.setText("Column");
	column.setWidth(100);
	column.addListener(SWT.Resize, e -> {
		if (column.getWidth() < 0) {
			throw new AssertionError();
		}
	});
}

for (int i = 0; i < 10; i++) {
	TreeItem item = new TreeItem(tree, 0);
	for (int j = 0; j < tree.getColumnCount(); j++) {
		item.setText(j, "Item");
	}
}

shell.pack();
shell.open();

while (!shell.isDisposed()) {
	if (!display.readAndDispatch()) {
		display.sleep();
	}
}

display.dispose();
```

The problem is that `column.getWidth()` returns -1.
This happens because `GTK.gtk_tree_view_column_get_fixed_width(handle)` returns -1.
I noticed that `GTK.gtk_tree_view_column_get_width(handle)` returns correct value.

I understand that this is a regression from Bug 568185 commit 0cb04a60.
@pauldpong Please have a look.

**Comment by jasonhy-wang** [comment]
Tested the issue on Fedora 36. Could not reproduce the error, double clicking column divider does not create a error on Fedora 36 and automatically resizes correctly

**Comment by Aamir3T** [comment]
The issue is reproducible on Ubuntu (20.04 and 22.04)
