### ISSUE TITLE
SWT Test Failure in MacOS x86

### ISSUE THREAD

**Issue by elsazac** [eclipse-platform/eclipse.platform.swt#567]
**Describe the bug**
[org.eclipse.swt.tests.junit](https://download.eclipse.org/eclipse/downloads/drops4/I20230302-0300/testresults/html/org.eclipse.swt.tests_ep427I-unit-mac64-java17_macosx.cocoa.x86_64_17.html#org.eclipse.swt.tests.junit) test  failing in mac64-java17_macosx.cocoa.x86

**Environment:**
1. Select the platform(s) on which the behavior is seen:
 - [ ] All OS
 - [ ] Windows
 - [ ] Linux
 - [x] macOS 

/cc @lshanmug

**Comment by lshanmug** [comment]
Seems to be an intermittent one as no code changes were made post RC1.

**Comment by elsazac** [comment]
There is this junit test failing in Mac OS x86. It seems to be an intermittent failure as Yesterday's build had none and no PR's were Merged since yesterday.

The below test failed in MacOS x86 in the I-Build [I20230517-1800](https://download.eclipse.org/eclipse/downloads/drops4/I20230517-1800)

```
Expected title and actual title do not match. Expected: Website Title Actual: file:///Users/genie.releng/workspace/AutomatedTests/ep428I-unit-mac64-java17/workarea/I20230517-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.0.v20230512-1002/data/testWebsiteWithTitle.html Test log: PLUGIN_PATH: /Users/genie.releng/workspace/AutomatedTests/ep428I-unit-mac64-java17/workarea/I20230517-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.0.v20230512-1002 URL: /Users/genie.releng/workspace/AutomatedTests/ep428I-unit-mac64-java17/workarea/I20230517-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.0.v20230512-1002/data/testWebsiteWithTitle.html TitleListener fired 

java.lang.AssertionError: 
Expected title and actual title do not match. 
Expected: Website Title 
Actual: file:///Users/genie.releng/workspace/AutomatedTests/ep428I-unit-mac64-java17/workarea/I20230517-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.0.v20230512-1002/data/testWebsiteWithTitle.html 
Test log: 
PLUGIN_PATH: /Users/genie.releng/workspace/AutomatedTests/ep428I-unit-mac64-java17/workarea/I20230517-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.0.v20230512-1002 
URL: /Users/genie.releng/workspace/AutomatedTests/ep428I-unit-mac64-java17/workarea/I20230517-1800/eclipse-testing/test-eclipse/Eclipse.app/Contents/Eclipse/plugins/org.eclipse.swt.tests_3.107.0.v20230512-1002/data/testWebsiteWithTitle.html 
TitleListener fired 
at org.junit.Assert.fail(Assert.java:89) 
at org.junit.Assert.assertTrue(Assert.java:42) 
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.validateTitleChanged(Test_org_eclipse_swt_browser_Browser.java:1067)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_browser_Browser.test_setUrl_local(Test_org_eclipse_swt_browser_Browser.java:985) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.base/java.lang.reflect.Method.invoke(Method.java:568) 
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59) 
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) 
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56) 
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) 
at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) 
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) 
at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61) 
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100) 
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366) 
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103) 
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63) 
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 
at org.junit.runners.Suite.runChild(Suite.java:128) 
at org.eclipse.test.TracingSuite.runChild(TracingSuite.java:290) 
at org.junit.runners.Suite.runChild(Suite.java:27) 
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331) 
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79) 
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329) 
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66) 
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293) 
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306) 
at org.junit.runners.ParentRunner.run(ParentRunner.java:413) 
at org.junit.runner.JUnitCore.run(JUnitCore.java:137) 
at org.junit.runner.JUnitCore.run(JUnitCore.java:115) 
at org.junit.vintage.engine.execution.RunnerExecutor.execute(RunnerExecutor.java:42) 
at org.junit.vintage.engine.VintageTestEngine.executeAllChildren(VintageTestEngine.java:80) 
at org.junit.vintage.engine.VintageTestEngine.execute(VintageTestEngine.java:72) 
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147) 
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127) 
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90) 
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55) 
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102) 
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54) 
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114) 
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86) 
at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86) 
at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53) 
at org.eclipse.test.EclipseTestRunner.runTests(EclipseTestRunner.java:212) 
at org.eclipse.test.EclipseTestRunner.run(EclipseTestRunner.java:187) 
at org.eclipse.test.CoreTestApplication.runTests(CoreTestApplication.java:53) 
at org.eclipse.test.CoreTestApplication.run(CoreTestApplication.java:35) 
at org.eclipse.test.CoreTestApplication.start(CoreTestApplication.java:44) 
at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203) 
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136) 
at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104) 
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402) 
at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) 
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
at java.base/java.lang.reflect.Method.invoke(Method.java:568) 
at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659) 
at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596) 
at org.eclipse.equinox.launcher.Main.run(Main.java:1467) 
at org.eclipse.equinox.launcher.Main.main(Main.java:1440) 
at org.eclipse.core.launcher.Main.main(Main.java:44) 
```

**Comment by akurtakov** [comment]
Is this bug still relevant?

**Comment by HeikoKlare** [comment]
The test failure does not occur anymore because the failing test has been disabled last year:
- #778

There is also #722 tracking the (two) failing tests and their current disablement, so I propose to close this one and keep the other tracking issue instead. I have updated the other issue to make clear that it is about test disablement instead of test failures now.
