### ISSUE TITLE
Webkit browser steals file/socket handles and never closes them 

### ISSUE THREAD

**Issue by basilevs** [eclipse-platform/eclipse.platform.swt#578]
Moved from [Bug 541763](https://bugs.eclipse.org/bugs/show_bug.cgi?id=541763)

The bug is reproducible on Java 17, Ubuntu 2022-12 (4.26.0), Eclipse 2022-12 (4.26.0)

### Test steps
Open a TCP port for listening
Open an embedded WebKit browser
Close the port

### Expected
The port is closed and reusable

### Actual
Port is in use by the WebKit browser.

[A minimal example in a form of a Junit Plug-in test](https://github.com/eclipse-platform/eclipse.platform.swt/files/10929814/bug541763_mcve.zip) [^1]
Excerpt:

```
    @Test
    public void ensureSocketsAreNotCaptured() throws IOException {
        InetSocketAddress bindpoint = new InetSocketAddress(InetAddress.getLocalHost(), port);
        try (Socket socket = new Socket()) {
            socket.bind(bindpoint);
            var subject = new Browser(shell, SWT.WEBKIT);
            fitToWindow(subject);
            subject.setText("Using port " + port);       
        } // Socket should be closed here        
        Assert.assertFalse("Port should be free", isPortTaken(port)); //Fails on Linux
    } 
```

### Workarounds
1. Never close ports
2. Close the browser before reopening the port

### Hypothesis
WebKit spawns support processes. Forked processes inherit memory and OS handles from the parent process. While following exec call overwrites memory, socket handles are kept even after exec. 
[The in-depth explanation of fork mechanism and its effect on sockets](https://stackoverflow.com/a/56650580/125562)
File handles are not affected because JVM uses a dedicated FD option when opening them. There is no (?) such support for sockets.

[^1]: Included launch configuration is platform specific, add your SWT native fragment before use, or delete the launch configuration

**Comment by akurtakov** [comment]
Is this still a problem?

**Comment by basilevs** [comment]
> Is this still a problem?

Reproducible exactly:

```
$ wget --output-document org.eclipse.swt.gtk.linux.aarch64_3.134.0.v20260515-1429.jar https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.40-I-builds/I20260601-0713/plugins/org.eclipse.swt.gtk.linux.aarch64_3.134.0.v20260515-1429.jar
$ wget --output-document  org.eclipse.swt_3.134.0.v20260515-1429.jar https://www.eclipse.org/downloads/download.php?file=/eclipse/updates/4.40-I-builds/I20260601-0713/plugins/org.eclipse.swt_3.134.0.v20260515-1429.jar
$ wget https://github.com/eclipse-platform/eclipse.platform.swt/files/10929814/bug541763_mcve.zip
$ wget https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
$ wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
$ unzip bug541763_mcve.zip
$ javac --class-path '*:com.spirent.bug541763/src' com.spirent.bug541763/src/com/spirent/Bug541763.java
$ java --class-path '*:com.spirent.bug541763/src' org.junit.runner.JUnitCore com.spirent.Bug541763
JUnit version 4.13.2
.
** (SWT:8370): WARNING **: 17:13:02.515: Disabled hardware acceleration because GTK failed to initialize GL: Unable to create a GL context.
E
Time: 0.39
There was 1 failure:
1) ensureSocketsAreNotCaptured(com.spirent.Bug541763)
java.lang.AssertionError: Port should be free
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertFalse(Assert.java:65)
	at com.spirent.Bug541763.ensureSocketsAreNotCaptured(Bug541763.java:117)

FAILURES!!!
Tests run: 1,  Failures: 1
$ java --version
openjdk 21.0.11 2026-04-21
OpenJDK Runtime Environment (build 21.0.11+10-1-22.04.2-Ubuntu)
OpenJDK 64-Bit Server VM (build 21.0.11+10-1-22.04.2-Ubuntu, mixed mode, sharing)
```
