### ISSUE TITLE
java.io.FileNotFoundException: /css/dark.css

### ISSUE THREAD

**Issue by minduch** [eclipse-platform/eclipse.platform.swt#581]
When Eclipse is tarted in dark mode, it alwyas shows this problem. The extra "[INFO]    11 Mar 2023  16:30:05.464  <system>  <stdout>" is from our system...

This is Eclipse 2023-03 RC1.

[INFO]    11 Mar 2023  16:30:05.464  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  java.io.FileNotFoundException: /css/dark.css
[INFO]    11 Mar 2023  16:30:05.464  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.osgi.storage.url.bundleentry.Handler.findBundleEntry(Handler.java:55)
[INFO]    11 Mar 2023  16:30:05.464  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.osgi.storage.url.BundleResourceHandler.openConnection(BundleResourceHandler.java:182)
[INFO]    11 Mar 2023  16:30:05.464  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at java.base/java.net.URL.openConnection(URL.java:1095)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.osgi.storage.url.BundleURLConverter.resolve(BundleURLConverter.java:55)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.core.runtime.FileLocator.resolve(FileLocator.java:288)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.core.internal.runtime.PlatformURLConverter.resolve(PlatformURLConverter.java:53)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.core.runtime.FileLocator.resolve(FileLocator.java:288)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:468)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.setTheme(ThemeEngine.java:436)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.e4.ui.css.swt.internal.theme.ThemeEngine.restore(ThemeEngine.java:607)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.setCSSTheme(PartRenderingEngine.java:1417)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.initializeStyling(PartRenderingEngine.java:1324)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1050)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
[INFO]    11 Mar 2023  16:30:05.465  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
[INFO]    11 Mar 2023  16:30:05.466  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
[INFO]    11 Mar 2023  16:30:05.467  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
[INFO]    11 Mar 2023  16:30:05.467  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
[INFO]    11 Mar 2023  16:30:05.832  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  
[INFO]    11 Mar 2023  16:30:05.832  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  !ENTRY org.eclipse.jface 2 0 2023-03-11 16:30:05.832
[INFO]    11 Mar 2023  16:30:05.832  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  !MESSAGE Keybinding conflicts occurred.  They may interfere with normal accelerator operation.
[INFO]    11 Mar 2023  16:30:05.832  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  !SUBENTRY 1 org.eclipse.jface 2 0 2023-03-11 16:30:05.832
[INFO]    11 Mar 2023  16:30:05.832  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  !MESSAGE A conflict occurred for CTRL+SHIFT+T:
[INFO]    11 Mar 2023  16:30:05.832  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  Binding(CTRL+SHIFT+T,
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	ParameterizedCommand(Command(org.eclipse.jdt.ui.navigate.open.type,Open Type,
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		Open a type in a Java editor,
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		Category(org.eclipse.ui.category.navigate,Navigate,null,true),
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.navigate.open.type"),
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		,,true),null),
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	org.eclipse.ui.defaultAcceleratorConfiguration,
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	org.eclipse.ui.contexts.window,,,system)
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  Binding(CTRL+SHIFT+T,
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	ParameterizedCommand(Command(org.eclipse.lsp4e.symbolinworkspace,Go to Symbol in Workspace,
[INFO]    11 Mar 2023  16:30:05.833  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		,
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		Category(org.eclipse.lsp4e.category,Language Servers,null,true),
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		WorkbenchHandlerServiceHandler("org.eclipse.lsp4e.symbolinworkspace"),
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		,,true),null),
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	org.eclipse.ui.defaultAcceleratorConfiguration,
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	org.eclipse.ui.contexts.window,,,system)
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  !SUBENTRY 1 org.eclipse.jface 2 0 2023-03-11 16:30:05.832
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  !MESSAGE A conflict occurred for ALT+SHIFT+R:
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  Binding(ALT+SHIFT+R,
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	ParameterizedCommand(Command(org.eclipse.jdt.ui.edit.text.java.rename.element,Rename - Refactoring ,
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		Rename the selected element,
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		Category(org.eclipse.jdt.ui.category.refactoring,Refactor - Java,Java Refactoring Actions,true),
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		WorkbenchHandlerServiceHandler("org.eclipse.jdt.ui.edit.text.java.rename.element"),
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		,,true),null),
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	org.eclipse.ui.defaultAcceleratorConfiguration,
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	org.eclipse.ui.contexts.window,,,system)
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  Binding(ALT+SHIFT+R,
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	ParameterizedCommand(Command(org.eclipse.ui.edit.rename,Rename,
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		Rename the selected item,
[INFO]    11 Mar 2023  16:30:05.834  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		Category(org.eclipse.ui.category.file,File,null,true),
[INFO]    11 Mar 2023  16:30:05.835  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		WorkbenchHandlerServiceHandler("org.eclipse.ui.edit.rename"),
[INFO]    11 Mar 2023  16:30:05.835  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  		,,true),null),
[INFO]    11 Mar 2023  16:30:05.835  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	org.eclipse.ui.defaultAcceleratorConfiguration,
[INFO]    11 Mar 2023  16:30:05.835  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  	org.eclipse.ui.contexts.window,,,system)
[INFO]    11 Mar 2023  16:30:07.307  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  
[INFO]    11 Mar 2023  16:30:07.307  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  !ENTRY org.eclipse.egit.ui 2 0 2023-03-11 16:30:07.306
[INFO]    11 Mar 2023  16:30:07.307  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  !MESSAGE Warning: The environment variable HOME is not set. The following directory will be used to store the Git
[INFO]    11 Mar 2023  16:30:07.307  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  user global configuration and to define the default location to store repositories: 'C:\Users\chris'. If this is
[INFO]    11 Mar 2023  16:30:07.307  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  not correct please set the HOME environment variable and restart Eclipse. Otherwise Git for Windows and
[INFO]    11 Mar 2023  16:30:07.307  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  EGit might behave differently since they see different configuration options.
[INFO]    11 Mar 2023  16:30:07.307  <system>  <stdout>  lThread[#84,stdout]/runnable@ForkJoinPool-1-worker-1  This warning can be switched off on the Team > Git > Confirmations and Warnings preference page.

**Comment by minduch** [comment]
Perhaps the classloader is changed too fast, resulting in this error. The "/css" file should perhaps not rely on the threads classloader?
