### ISSUE TITLE
Test_org_eclipse_swt_widgets_Button.test_setOrientation fails on Mac

### ISSUE THREAD

**Issue by iloveeclipse** [eclipse-platform/eclipse.platform.swt#591]
See https://download.eclipse.org/eclipse/downloads/drops4/I20230316-1800/testresults/html/org.eclipse.swt.tests_ep428I-unit-mac64-java17_macosx.cocoa.x86_64_17.html

I can't remember it failing before, seem some recent change caused it.

```
expected:<67108864> but was:<33554432>

java.lang.AssertionError: expected:<67108864> but was:<33554432>
at org.junit.Assert.fail(Assert.java:89)
at org.junit.Assert.failNotEquals(Assert.java:835)
at org.junit.Assert.assertEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:633)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_widgets_Button.test_setOrientation(Test_org_eclipse_swt_widgets_Button.java:192)
```

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [ ] Windows
- - [ ] Linux
- - [x] macOS

**Comment by Phillipus** [comment]
`Button#setOrientation` (actually `Control#setOrientation`) does nothing. Orientation should be set in the constructor:

`Button button = new Button(shell, SWT.PUSH | SWT.RIGHT_TO_LEFT);`

**Comment by iloveeclipse** [comment]
@Phillipus : thanks for looking into.

@mbooth101 : would you please fix the new test to not run on Mac, see comment above?

**Comment by mbooth101** [comment]
I will take a look -- I did not notice any MacOS test failures on the original PR: https://github.com/eclipse-platform/eclipse.platform.swt/actions/runs/4366256928/jobs/7636013659?pr=555

Are tests not actually run there?

**Comment by iloveeclipse** [comment]
> It seems like the GitHub job is always green even when there is test failure!!!! Can that be fixed?

Before we can fix an issue, it should be 1) found & 2) reported. We are at 1) now :-)
Please create an issue.

**Comment by mbooth101** [comment]
I will do so, but I meant more like "is it within the realm of possibility?" and some limitation of GitHub :-)

**Comment by mbooth101** [comment]
> 
> **Obviously** it is :-) 

I'm using github action results to check I don't accidentally break other platforms on which I can't easily test on (like Mac) but I could be wrong about the reasons for the github actions. Maybe it's only intended to check if it builds at all? It's not obvious to me if the current behaviour is intentional or not ;-)

**Comment by elsazac** [comment]
Verified this in Mac OS aarch64 Ventura 13.2.1.

Build details are as follows:
Eclipse SDK
Version: 2023-06 (4.28)
Build id: I20230405-1800
OS: Mac OS X, v.13.2.1, aarch64 / cocoa
