### ISSUE TITLE
Compare view crashing on yml files

### ISSUE THREAD

**Issue by Kiiv** [eclipse-platform/eclipse.platform.swt#636]
Hi, 
don't know if I'm at the right place...

**Describe the bug**

When opening a compare view (local mode, with remote revision, or whatever) of two yaml files (.yml extension), the compare view is empty.

Got the folowing error in the .metadata/.log :
```
!ENTRY org.eclipse.ui 4 0 2023-04-18 14:50:49.827
!MESSAGE Unhandled event loop exception
!STACK 0
java.lang.ClassCastException: class org.eclipse.jface.text.source.SourceViewer cannot be cast to class org.eclipse.jface.text.source.projection.ProjectionViewer (org.eclipse.jface.text.source.SourceViewer and org.eclipse.jface.text.source.projection.ProjectionViewer are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @6c7bc8ac)
	at org.eclipse.lsp4e.operations.folding.LSPFoldingReconcilingStrategy.install(LSPFoldingReconcilingStrategy.java:173)
	at org.eclipse.ui.internal.genericeditor.CompositeReconcilerStrategy.install(CompositeReconcilerStrategy.java:78)
	at org.eclipse.jface.text.reconciler.Reconciler.install(Reconciler.java:175)
	at org.eclipse.ui.internal.genericeditor.CompositeReconciler.install(CompositeReconciler.java:56)
	at org.eclipse.jface.text.source.SourceViewer.configure(SourceViewer.java:504)
	at org.eclipse.ui.internal.genericeditor.compare.GenericEditorMergeViewer.configureTextViewer(GenericEditorMergeViewer.java:68)
	at org.eclipse.ui.internal.genericeditor.compare.GenericEditorMergeViewer$1.inputDocumentChanged(GenericEditorMergeViewer.java:50)
	at org.eclipse.jface.text.TextViewer.fireInputDocumentChanged(TextViewer.java:2849)
	at org.eclipse.jface.text.TextViewer.setDocument(TextViewer.java:2890)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:682)
	at org.eclipse.jface.text.source.SourceViewer.setDocument(SourceViewer.java:622)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer$ContributorInfo.updateViewerDocument(TextMergeViewer.java:807)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer$ContributorInfo.internalSetDocument(TextMergeViewer.java:762)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer$ContributorInfo.setDocument(TextMergeViewer.java:679)
	at org.eclipse.compare.contentmergeviewer.TextMergeViewer.updateContent(TextMergeViewer.java:3029)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.internalRefresh(ContentMergeViewer.java:793)
	at org.eclipse.compare.contentmergeviewer.ContentMergeViewer.inputChanged(ContentMergeViewer.java:701)
	at org.eclipse.jface.viewers.ContentViewer.setInput(ContentViewer.java:282)
	at org.eclipse.compare.CompareViewerSwitchingPane.setInput(CompareViewerSwitchingPane.java:268)
	at org.eclipse.compare.internal.CompareContentViewerSwitchingPane.setInput(CompareContentViewerSwitchingPane.java:202)
	at org.eclipse.compare.CompareEditorInput.internalSetContentPaneInput(CompareEditorInput.java:806)
	at org.eclipse.compare.CompareEditorInput.lambda$8(CompareEditorInput.java:747)
	at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:67)
	at org.eclipse.compare.CompareEditorInput.feed1(CompareEditorInput.java:742)
	at org.eclipse.compare.CompareEditorInput.feedInput(CompareEditorInput.java:720)
	at org.eclipse.compare.CompareEditorInput.createContents(CompareEditorInput.java:543)
	at org.eclipse.compare.internal.CompareEditor.createCompareControl(CompareEditor.java:448)
	at org.eclipse.compare.internal.CompareEditor$1.lambda$0(CompareEditor.java:366)
	at org.eclipse.ui.internal.PendingSyncExec.run(PendingSyncExec.java:68)
	at org.eclipse.ui.internal.UILockListener.doPendingWork(UILockListener.java:172)
	at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
	at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:132)
	at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:5040)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4520)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1155)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1046)
	at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:643)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:550)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:171)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:152)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

**To Reproduce**
Create two .yml files and compare them.

**Expected behavior**
A view of the differences between the two files.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [] All OS
- - [ ] Windows
- - [ X] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
I tried to change the default editor of yml files but I always got the error.

3. JRE/JDK version
 Temurin 17

Installation details :
```
  Buildship: Eclipse Plug-ins for Gradle	3.1.6.v20220511-1359	org.eclipse.buildship.feature.group	Eclipse Buildship
  Bytecode Outline View	1.1.0.v20230117-1348	org.eclipse.jdt.bcoview.feature.feature.group	Eclipse.org
  EclEmma Java Code Coverage	3.1.6.202206011447	org.eclipse.eclemma.feature.feature.group	Eclipse EclEmma
  Eclipse IDE for Java Developers	4.27.0.20230309-1200	epp.package.java	Eclipse Packaging Project
  Eclipse Java Development Tools	3.19.0.v20230302-0300	org.eclipse.jdt.feature.group	Eclipse.org
  Git integration for Eclipse	6.5.0.202303070854-r	org.eclipse.egit.feature.group	Eclipse EGit
  GWT 2.8.2 SDK	2.8.0.202303131102	com.gwtplugins.eclipse.sdkbundle.gwt28.feature.feature.group	GWT Eclipse Plugin
  GWT Eclipse Plugin	4.0.0.202302020242	com.gwtplugins.eclipse.suite.v3.feature.feature.group	GWT Eclipse Plugin
  Java implementation of Git	6.5.0.202303070854-r	org.eclipse.jgit.feature.group	Eclipse JGit
  JNA Library	4.1.0.v06022015_1911	net.java.dev.jna.feature.group	null
  JustJ JRE for IDE Packages	17.0.0.v20230203-0825	org.eclipse.justj.epp.feature.group	Eclipse JustJ
  M2E - Maven Integration for Eclipse	2.2.1.20230307-1553	org.eclipse.m2e.feature.feature.group	Eclipse.org - m2e
  M2E - POM Editor using LemMinX language server (includes Incubating components)	2.0.3.20230202-1631	org.eclipse.m2e.lemminx.feature.feature.group	Eclipse.org - m2e
  M2E - SLF4J over Logback Logging	2.1.1.20230106-1511	org.eclipse.m2e.logback.feature.feature.group	Eclipse.org - m2e
  Marketplace Client	1.10.1.v20221110-1841	org.eclipse.epp.mpc.feature.group	Eclipse Marketplace Client
  Mylyn WikiText	3.0.46.202301111837	org.eclipse.mylyn.wikitext_feature.feature.group	Eclipse Mylyn
  Oomph Setup	1.27.0.v20230304-1248	org.eclipse.oomph.setup.feature.group	Eclipse Oomph Project
  PyDev for Eclipse	10.1.3.202301231743	org.python.pydev.feature.feature.group	Fabio Zadrozny
  SonarLint for Eclipse	7.9.0.66038	org.sonarlint.eclipse.feature.feature.group	SonarSource
  Source Map Editor Feature	2.1.0.202303101717	com.github.sdbg.feature.feature.group	null
  SQL Editor	1.4.0	de.jcup.sqleditor.feature.group	Albert Tregnaghi
  Subversive SVN Connectors	6.0.4.I20161211-1700	org.polarion.eclipse.team.svn.connector.feature.group	Polarion Software
  Subversive SVN Integration for the M2E Project (Optional)	4.8.0.v20230227-2140	org.eclipse.team.svn.m2e.feature.group	Eclipse.org
  Subversive SVN Team Provider	4.8.0.v20230227-2140	org.eclipse.team.svn.feature.group	Eclipse.org
  Subversive SVN Team Provider Core	4.8.0.v20230227-2140	org.eclipse.team.svn.core.feature.group	Eclipse.org
  Subversive SVN Team Provider UI Capabilities	4.0.0.v20230227-2140	org.eclipse.team.svn.ui.capabilities.feature.group	Eclipse.org
  SVNKit 1.10.x Implementation (Optional)	6.1.0	org.polarion.eclipse.team.svn.connector.svnkit1_10.feature.group	osspit.org
  SVNKit Library	1.10.6.r10830	org.tmatesoft.svnkit.feature.group	TMate Software
  Tip of the Day UI Feature	0.3.100.v20230109-1247	org.eclipse.tips.feature.feature.group	Eclipse.org
  TM Terminal	11.1.0.202212091724	org.eclipse.tm.terminal.feature.feature.group	Eclipse CDT
  Wild Web Developer HTML, CSS, JSON, Yaml, JavaScript, TypeScript, Node tools	1.0.4.202304061732	org.eclipse.wildwebdeveloper.feature.feature.group	Eclipse Wild Web Developer project
  Wild Web Developer XML tools	1.0.3.202303142004	org.eclipse.wildwebdeveloper.xml.feature.feature.group	Eclipse Wild Web Developer project
```

**Comment by mickaelistria** [comment]
Duplicates https://github.com/eclipse/lsp4e/issues/608
