### ISSUE TITLE
[Win32] NPE in Menu.wmTimer

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#655]
**Describe the bug**
A user of our SWT-based application reported following exception:
```
java.lang.NullPointerException: Cannot read field "handle" because "this.selectedMenuItem.parent" is null
	at org.eclipse.swt.widgets.Menu.wmTimer(Menu.java:1356)
	at org.eclipse.swt.widgets.Control.WM_TIMER(Control.java:5656)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4830)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2286)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5035)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:508)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4847)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2286)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5035)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:508)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4847)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2286)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5035)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3649)
...
```
It is following code:
```java
LRESULT wmTimer (long wParam, long lParam) {
	if (wParam == ID_TOOLTIP_TIMER) {
		POINT pt = new POINT ();
		OS.GetCursorPos (pt);
		if (selectedMenuItem != null) {
			RECT rect = new RECT ();
			boolean success = OS.GetMenuItemRect (0, selectedMenuItem.parent.handle, selectedMenuItem.index, rect); // <-- NPE here
			if (!success) return null;
```

**To Reproduce**
I can't reproduce.

**Expected behavior**
The code should not crash if `selectedMenuItem.parent == null`.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS

**Comment by deepika-u** [comment]
I felt we can go ahead with this fix when looked at the change.

**Comment by deepika-u** [comment]
@tmssngr 
Have you got this verified and can this be closed now?

**Comment by tmssngr** [comment]
#deepika-u Yes, the user who had this problem confirmed that my change fixed the problem.

**Comment by deepika-u** [comment]
I dont have access to close, can you please close it.

**Comment by tmssngr** [comment]
Ah, it already had been cherry-picked.
