### ISSUE TITLE
[mac] github verification build fails randomly

### ISSUE THREAD

**Issue by jukzi** [eclipse-platform/eclipse.platform.swt#705]
MAC only: On the first run "Verify MacOS with Java-17" almost always fails with
71 errors like

```
expected:<Shell {} [layout=null]> but was:<null>
java.lang.AssertionError: expected:<Shell {} [layout=null]> but was:<null>
	at org.junit.Assert.fail(Assert.java:89)
	at org.junit.Assert.failNotEquals(Assert.java:835)
	at org.junit.Assert.assertEquals(Assert.java:120)
	at org.junit.Assert.assertEquals(Assert.java:146)

```
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/51790620/3d2d5beb-fd26-4cf8-a391-253c98d7f913)

After a Re-run of failed jobs sometimes all tests pass:
![image](https://github.com/eclipse-platform/eclipse.platform.swt/assets/51790620/1e753443-c6f7-445a-8c4e-099728fd4d5b)

**Comment by HeikoKlare** [comment]
We did not have this kind of issue with the MacOS GHA runs in the (even not so) recent past. Thus closing this issue as not reproducible.
