### ISSUE TITLE
Assertion in org.eclipse.swt.graphics.Image.createGdipImage (memHdc == 0)

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#780]
**Describe the bug**
A couple of users of our SWT-based applications have reported following exception over the last versions (some repeatedly):
```
org.eclipse.swt.SWTError: No more handles
	at org.eclipse.swt.SWT.error(SWT.java:4944)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.graphics.Image.createGdipImage(Image.java:983)
	at org.eclipse.swt.graphics.GC.drawImage(GC.java:1002)
	at org.eclipse.swt.graphics.GC.drawImage(GC.java:993)
... (our code)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4257)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1066)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1090)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1075)
	at org.eclipse.swt.widgets.Tree.CDDS_ITEMPOSTPAINT(Tree.java:867)
	at org.eclipse.swt.widgets.Tree.wmNotifyChild(Tree.java:7468)
	at org.eclipse.swt.widgets.Control.wmNotify(Control.java:5800)
	at org.eclipse.swt.widgets.Composite.wmNotify(Composite.java:1961)
	at org.eclipse.swt.widgets.Control.WM_NOTIFY(Control.java:5368)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4802)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5043)
	at org.eclipse.swt.internal.win32.OS.CallWindowProc(Native Method)
	at org.eclipse.swt.widgets.Tree.callWindowProc(Tree.java:1542)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4847)
	at org.eclipse.swt.widgets.Tree.windowProc(Tree.java:6059)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5043)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3649)
... (our code)
```
Some write it happened immediately after waking up from hibernation.

**To Reproduce**
Unfortunately, I don't know a reliable way of reproducing it.

**Expected behavior**
Not throwing an assertion.

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

2. Additional OS info (e.g. OS version, Linux Desktop, etc)
Windows 10 and Windows 7, no report for Windows 11 yet.

**Comment by SyntevoAlex** [comment]
I was able to reproduce that in a simple С++ snippet, along these lines
```
for (;;)
{
	HDC screenDC = GetDC(0);
	if (0 == screenDC)
	{
		char buffer[256];
		sprintf_s(buffer, "%d = GetDC()\n", GetLastError());
		OutputDebugStringA(buffer);
		continue;
	}

	bool isError11 = false;
	for (int i = 0; i < 1024; i++)
	{
		HDC compatDC = CreateCompatibleDC(screenDC);
		if (0 == compatDC)
		{
			isError11 = true;
			break;
		}
		DeleteDC(compatDC);
	}

	bool isError12 = false;
	if (isError11)
	{
		HDC compatDC = CreateCompatibleDC(screenDC);
		if (compatDC)
			DeleteDC(compatDC);
		else
			isError12 = true;
	}

	bool isError21 = false;
	if (isError11)
	{
		HDC screenDC2 = GetDC(0);
		HDC compatDC = CreateCompatibleDC(screenDC2);
		if (compatDC)
			DeleteDC(compatDC);
		else
			isError21 = true;

		ReleaseDC(0, screenDC2);
	}

	bool isError13 = false;
	if (isError11)
	{
		HDC compatDC = CreateCompatibleDC(screenDC);
		if (compatDC)
			DeleteDC(compatDC);
		else
			isError13 = true;
	}

	if (isError11)
	{
		char buffer[256];
		sprintf_s(
			buffer,
			"CreateCompatibleDC() = %c/%c/%c/%c\n",
			isError11 ? 'N' : 'Y',
			isError12 ? 'N' : 'Y',
			isError21 ? 'N' : 'Y',
			isError13 ? 'N' : 'Y'
		);
		OutputDebugStringA(buffer);
	}

	ReleaseDC(0, screenDC);
}
```

When running this code while sleeping/waking computer, it sometimes fails.

I kernel debugged Windows and found that this is a Windows bug.

When computer wakes up, `win32kfull!PowerOnGdi()` is executed, which will
1) Enable GDI
2) Enable display device

When computer sleeps, `PowerOffGdi()` is executed, which will
1) Disable display device
2) Disable GDI

In `win32kbase!GreCreateDisplayDC()`, there's a condition like

```
if (GDI_enabled && !device_enabled)
{
	return error;
}
```

It's easy to see how there's a small window of race condition where GDI is enabled but device is disabled when both sleeping or waking. If `CreateCompatibleDC()` is called in this small window, it unexpectedly fails.

I tried to reproduce it in Java, but Java is slow, so reproducing is harder. I didn't only had the patience to sleep/wake for some 5 minutes and gave up trying to reproduce, because the problem is already clear to me.

**Comment by SyntevoAlex** [comment]
The workaround would be to wrap 'CreateCompatibleDC()' into a helper that would repeat it a few times after failure.
The race window is very small, so even repeating for 1ms should be good enough.
