### ISSUE TITLE
[Win] Possible NPE in org.eclipse.swt.widgets.Menu#wmTimer

### ISSUE THREAD

**Issue by tmssngr** [eclipse-platform/eclipse.platform.swt#821]
**Describe the bug**
A user reported following exception
```
java.lang.NullPointerException: Cannot read field "handle" because "this.selectedMenuItem.parent" is null
	at org.eclipse.swt.widgets.Menu.wmTimer(Menu.java:1356)
	at org.eclipse.swt.widgets.Control.WM_TIMER(Control.java:5656)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4830)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2286)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5043)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:508)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4847)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2286)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5035)
	at org.eclipse.swt.internal.win32.OS.DefWindowProc(Native Method)
	at org.eclipse.swt.widgets.Shell.callWindowProc(Shell.java:508)
	at org.eclipse.swt.widgets.Control.windowProc(Control.java:4847)
	at org.eclipse.swt.widgets.Canvas.windowProc(Canvas.java:340)
	at org.eclipse.swt.widgets.Decorations.windowProc(Decorations.java:1480)
	at org.eclipse.swt.widgets.Shell.windowProc(Shell.java:2286)
	at org.eclipse.swt.widgets.Display.windowProc(Display.java:5035)
	at org.eclipse.swt.internal.win32.OS.DispatchMessage(Native Method)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3649)
```
for following code
```java
LRESULT wmTimer (long wParam, long lParam) {
	if (wParam == ID_TOOLTIP_TIMER) {
		POINT pt = new POINT ();
		OS.GetCursorPos (pt);
		if (selectedMenuItem != null) {
			RECT rect = new RECT ();
			boolean success = OS.GetMenuItemRect (0, selectedMenuItem.parent.handle, selectedMenuItem.index, rect); // << here
			if (!success) return null;
			if (OS.PtInRect (rect, pt)) {
				// Mouse cursor is within the bounds of menu item
				selectedMenuItem.showTooltip (pt.x, pt.y + OS.GetSystemMetrics(OS.SM_CYCURSOR) / 2 + 5);
			} else {
				/*
				 * Mouse cursor is outside the bounds of the menu item:
				 * Keyboard or mnemonic was used to select menu item
				 */
				selectedMenuItem.showTooltip ((rect.right + rect.left) / 2, rect.bottom + 5);
			}
		}
	}

	return null;
}
```

**To Reproduce**
Don't know.

**Expected behavior**
No exception

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS

**Comment by tmssngr** [comment]
Sorry, duplicate of bug 655.
