### ISSUE TITLE
org.eclipse.swt.tests.junit.Test_org_eclipse_swt_widgets_Text failing in Windows

### ISSUE THREAD

**Issue by elsazac** [eclipse-platform/eclipse.platform.swt#876]
**Describe the bug**

[org.eclipse.swt.tests.junit](https://download.eclipse.org/eclipse/downloads/drops4/I20231109-0710/testresults/html/org.eclipse.swt.tests_ep430I-unit-win32-java17_win32.win32.x86_64_17.html#org.eclipse.swt.tests.junit) failing in win32.x86_64

**Environment:**
1. Select the platform(s) on which the behavior is seen:
- - [ ] All OS
- - [x] Windows
- - [ ] Linux
- - [ ] macOS 

```
expected:<[]> but was:<[01567890]>

org.junit.ComparisonFailure: expected:<[]> but was:<[01567890]>
at org.junit.Assert.assertEquals(Assert.java:117)
at org.junit.Assert.assertEquals(Assert.java:146)
at org.eclipse.swt.tests.junit.Test_org_eclipse_swt_widgets_Text.test_cut(Test_org_eclipse_swt_widgets_Text.java:378)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
```

**Comment by SyntevoAlex** [comment]
Duplicate of https://github.com/eclipse-platform/eclipse.platform.swt/issues/106

**Comment by deepika-u** [comment]
Can this also be closed?
As i see 
<testcase classname="org.eclipse.swt.tests.junit.Test_org_eclipse_swt_widgets_Text" name="test_cut" time="0.015"/>

=> https://download.eclipse.org/eclipse/downloads/drops4/I20250108-1800/testresults/xml/org.eclipse.swt.tests_ep435I-unit-win32-x86_64-java21_win32.win32.x86_64_21.xml
